library(tidyverse)
library(furrr)
library(dynmethods)
library(dynwrap)

files <- list.files("containers", pattern = "Dockerfile", recursive = TRUE, full.names = TRUE)

# create singularity scripts from dockerfiles
walk(files, function(file) {
  new_file <- gsub("containers/([^/]*)/.*", "containers/\\1/Singularity.\\1", file)
  lines <-
    readr::read_lines(file) %>%
    discard(~ grepl("^ *$", .))

  add_header <- function(lines, header) {
    if (length(lines) > 0) {
      c(header, lines, "")
    } else {
      c()
    }
  }

  from <- str_subset(lines, "^FROM ") %>% str_replace_all("FROM ", "From: ")
  environment <- str_subset(lines, "^ENV ") %>% str_replace_all("ENV ", "    export ") %>% add_header("%environment")
  labels <- str_subset(lines, "^LABEL ") %>% str_replace_all("LABEL ", "    ") %>% add_header("%labels")
  post <- str_subset(lines, "^RUN ") %>% str_replace_all("RUN ", "    ") %>% add_header("%post")
  files <- str_subset(lines, "^ADD ") %>% str_replace_all("ADD ", "    ") %>% add_header("%files")
  runscript <- str_subset(lines, "^ENTRYPOINT ") %>% str_replace_all("ENTRYPOINT ", "    exec ") %>% add_header("%runscript")

  sing_lines <- c(
    "########################################################################",
    "##                      DO NOT EDIT THIS FILE!                        ##",
    "##     This file was automatically generated from the dockerfile.     ##",
    "## Run dynmethods/data-raw/convert_dockerfiles.R to update this file. ##",
    "########################################################################",
    "",
    "Bootstrap: shub",
    "",
    from,
    "",
    environment,
    labels,
    post,
    files,
    runscript
  )

  readr::write_lines(sing_lines, new_file)
})
