FROM dynverse/dynwrap:bioc

LABEL version 0.1.0.1

RUN R -e 'devtools::install_cran("destiny")'

RUN git clone https://github.com/CABSEL/CALISTA.git; rm -rf CALISTA/.git; find CALISTA -type f \( -iname \*.zip -o -iname \*.csv -o -iname \*.txt \) -exec rm {} +


RUN apt-get update && apt-get install -y libcgal-dev libglu1-mesa-dev libglu1-mesa-dev libjpeg-dev libtiff-dev tcl-dev

RUN Rscript CALISTA/CALISTA-R/install_packs.R

# Patch was generated by making changes in the calista git repository,
# and then running:
# git diff --no-prefix > ~/Workspace/dynverse/dynmethods/containers/calista/calista.patch

RUN cd CALISTA; wget https://gist.githubusercontent.com/rcannood/ed97cacc2f373de6f3a6bb7320e2c677/raw/935044855cd204aee6eba821367b95669bb14784/calista.patch; patch -p0 calista.patch

ADD . /code

ENTRYPOINT /code/run.sh
