######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Angle
#' 
#' @description
#' Will generate a trajectory using Angle.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_angle).
#' 
#' 
#' 
#' 
#' @param dimred discrete; Which dimensionality reduction method to use. (default:
#' `"pca"`; values: {`"pca"`, `"mds"`, `"tsne"`, `"ica"`, `"lle"`,
#' `"landmark_mds"`, `"mds_sammon"`, `"mds_isomds"`, `"mds_smacof"`, `"umap"`,
#' `"dm_diffusionMap"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_angle <- function(
    dimred = "pca",
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/ti_angle",
    version = method_versions[["dynverse/ti_angle"]],
    config = config
  )(
    dimred = dimred
  )
}

