######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Angle
#' 
#' @description
#' Will generate a trajectory using Angle.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_angle).
#' 
#' 
#' 
#' 
#' @param dimred Which dimensionality reduction method to use. Domain: {pca, mds,
#' tsne, ica, lle, landmark_mds, mds_sammon, mds_isomds, mds_smacof, umap,
#' dm_diffusionMap, dm_destiny}. Default: pca. Format: character.
#' 
#' @keywords method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_angle <- function(
    dimred = "pca"
) {
  method_choose_backend(
    package_repository = NULL,
    package_name = NULL,
    function_name = NULL,
    package_version = NULL,
    container_id = "dynverse/ti_angle:v0.9.9.02"
  )(
    dimred = dimred
  )
}

