######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using CALISTA
#' 
#' @description
#' Will generate a trajectory using [CALISTA](https://doi.org/10.1101/257550).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/calista).
#' The original code of this method is available
#' [here](https://github.com/CABSEL/CALISTA).
#' 
#' @references Papili Gao, N., Hartmann, T., Gunawan, R., 2018. CALISTA:
#' Clustering And Lineage Inference in Single-Cell Transcriptional Analysis.
#' 
#' @param runs integer; Number of independent runs of greedy algorithm (default:
#' `50L`; range: from `20L` to `100L`)
#' @param max_iter integer; Number of iterations in greedy algorithm (default:
#' `100L`; range: from `20L` to `400L`)
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_calista <- function(
    runs = 50L,
    max_iter = 100L,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/calista",
    run_environment = run_environment,
    runs = runs,
    max_iter = max_iter
  )
}

