######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using cellTree with vem
#' 
#' @description
#' Will generate a trajectory using [cellTree with
#' vem](https://doi.org/10.1186/s12859-016-1175-6).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_celltree_vem).
#' The original code of this method is available
#' [here](https://bioconductor.org/packages/release/bioc/html/cellTree.html).
#' 
#' @references duVerle, D.A., Yotsukura, S., Nomura, S., Aburatani, H., Tsuda, K.,
#' 2016. CellTree: an R/bioconductor package to infer the hierarchical structure
#' of cell populations from single-cell RNA-seq data. BMC Bioinformatics 17.
#' 
#' @param method discrete; (default: `"VEM"`; values: {`"VEM"`})
#' @param sd_filter numeric; (default: `0.5`; range: from `0.01` to `5`)
#' @param absolute_width numeric; (default: `0`; range: from `NULL` to `NULL`)
#' @param width_scale_factor numeric; (default: `1.5`; range: from `0.1` to `100`)
#' @param outlier_tolerance_factor numeric; (default: `0.1`; range: from `1e-04`
#' to `1000`)
#' @param rooting_method discrete; (default: `"null"`; values: {`"longest.path"`,
#' `"center.start.group"`, `"average.start.group"`, `"null"`})
#' @param num_topics integer; (default: `4`; range: from `2` to `15`)
#' @param tot_iter numeric; (default: `1e+06`; range: from `10000` to `1e+07`)
#' @param tolerance numeric; (default: `1e-05`; range: from `1e-07` to `0.001`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_celltree_vem <- function(
    method = "VEM",
    sd_filter = 0.5,
    absolute_width = 0,
    width_scale_factor = 1.5,
    outlier_tolerance_factor = 0.1,
    rooting_method = "null",
    num_topics = 4,
    tot_iter = 1e+06,
    tolerance = 1e-05,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/ti_celltree_vem",
    version = method_versions[["dynverse/ti_celltree_vem"]],
    config = config
  )(
    method = method,
    sd_filter = sd_filter,
    absolute_width = absolute_width,
    width_scale_factor = width_scale_factor,
    outlier_tolerance_factor = outlier_tolerance_factor,
    rooting_method = rooting_method,
    num_topics = num_topics,
    tot_iter = tot_iter,
    tolerance = tolerance
  )
}

