######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using CellRouter
#' 
#' @description
#' Will generate a trajectory using
#' [CellRouter](https://doi.org/10.1038/s41467-018-03214-y).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/cellrouter).
#' The original code of this method is available
#' [here](https://github.com/edroaldo/cellrouter).
#' 
#' @references Lummertz da Rocha, E., Rowe, R.G., Lundin, V., Malleshaiah, M.,
#' Jha, D.K., Rambo, C.R., Li, H., North, T.E., Collins, J.J., Daley, G.Q., 2018.
#' Reconstruction of complex single-cell trajectories using CellRouter. Nature
#' Communications 9.
#' 
#' @param ndim_pca integer; Number of principlal components to compute (default:
#' `20L`; range: from `2L` to `100L`)
#' @param ndim_tsne integer; Number of tsne dimensions to compute (default: `11L`;
#' range: from `2L` to `100L`)
#' @param max_iter integer; Maximal number of tsne iterations (default: `1000L`;
#' range: from `100L` to `100000L`)
#' @param cluster_method discrete; Method to use for clustering (default:
#' `"graph.clustering"`; values: {`"graph.clustering"`, `"model.clustering"`})
#' @param k_clustering integer; Number of nearest neighbors to build a k-nearest
#' neighbors graph for clustering (default: `20L`; range: from `2L` to `1000L`)
#' @param ndim_pca_clustering integer; Number of PCA dimensions used for k-nearest
#' neighbors graph for clustering (default: `20L`; range: from `2L` to `100L`)
#' @param k_knn integer; Number of nearest neighbors to build a k-nearest
#' neighbors graph for knn (default: `10L`; range: from `2L` to `1000L`)
#' @param ndim_pca_knn integer; Number of PCA dimensions used for knn (default:
#' `20L`; range: from `2L` to `100L`)
#' @param sim_type discrete; Similarity type for knn (default: `"jaccard"`;
#' values: {`"jaccard"`})
#' @param distance_method_paths discrete; Distance method for paths (default:
#' `"graph"`; values: {`"euclidean"`, `"maximum"`, `"manhattan"`, `"canberra"`,
#' `"binary"`, `"graph"`})
#' @param ranks discrete; How to rank the paths (default: `"rank"`; values:
#' {`"path_cost"`, `"path_flow"`, `"rank"`, `"length"`})
#' @param num_cells integer; Trajectories should contain at least num.cells
#' (default: `3L`; range: from `3L` to `100L`)
#' @param neighs integer; The size of the neighborhood in kNN graph used to
#' smoothen kinetic profiles (default: `3L`; range: from `2L` to `100L`)
#' @param perplexity numeric; Perplexity parameter for tsne (default: `30L`;
#' range: from `5L` to `100L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_cellrouter <- function(
    ndim_pca = 20L,
    ndim_tsne = 11L,
    max_iter = 1000L,
    cluster_method = "graph.clustering",
    k_clustering = 20L,
    ndim_pca_clustering = 20L,
    k_knn = 10L,
    ndim_pca_knn = 20L,
    sim_type = "jaccard",
    distance_method_paths = "graph",
    ranks = "rank",
    num_cells = 3L,
    neighs = 3L,
    perplexity = 30L,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = repo_digests[["dynverse/cellrouter"]],
    config = config
  )(
    ndim_pca = ndim_pca,
    ndim_tsne = ndim_tsne,
    max_iter = max_iter,
    cluster_method = cluster_method,
    k_clustering = k_clustering,
    ndim_pca_clustering = ndim_pca_clustering,
    k_knn = k_knn,
    ndim_pca_knn = ndim_pca_knn,
    sim_type = sim_type,
    distance_method_paths = distance_method_paths,
    ranks = ranks,
    num_cells = num_cells,
    neighs = neighs,
    perplexity = perplexity
  )
}

