######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using cellTree with maptpx
#' 
#' @description
#' Will generate a trajectory using [cellTree with
#' maptpx](https://doi.org/10.1186/s12859-016-1175-6).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/celltree_maptpx).
#' The original code of this method is available
#' [here](https://bioconductor.org/packages/release/bioc/html/cellTree.html).
#' 
#' @references duVerle, D.A., Yotsukura, S., Nomura, S., Aburatani, H., Tsuda, K.,
#' 2016. CellTree: an R/bioconductor package to infer the hierarchical structure
#' of cell populations from single-cell RNA-seq data. BMC Bioinformatics 17.
#' 
#' @param method discrete; (default: `"maptpx"`; values: {`"maptpx"`})
#' @param sd_filter numeric; (default: `0.5`; range: from `0.01` to `5`)
#' @param absolute_width numeric; (default: `0`; range: from `NULL` to `NULL`)
#' @param width_scale_factor numeric; (default: `1.5`; range: from `0.1` to `100`)
#' @param outlier_tolerance_factor numeric; (default: `0.1`; range: from `1e-04`
#' to `1000`)
#' @param rooting_method discrete; (default: `"null"`; values: {`"longest.path"`,
#' `"center.start.group"`, `"average.start.group"`, `"null"`})
#' @param num_topics_lower integer; (default: `2`; range: from `2` to `15`)
#' @param num_topics_upper integer; (default: `15`; range: from `2` to `15`)
#' @param tot_iter numeric; (default: `1e+06`; range: from `10000` to `1e+07`)
#' @param tolerance numeric; (default: `0.05`; range: from `0.001` to `0.5`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_celltree_maptpx <- function(
    method = "maptpx",
    sd_filter = 0.5,
    absolute_width = 0,
    width_scale_factor = 1.5,
    outlier_tolerance_factor = 0.1,
    rooting_method = "null",
    num_topics_lower = 2,
    num_topics_upper = 15,
    tot_iter = 1e+06,
    tolerance = 0.05,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/celltree_maptpx@sha256:b52dc7d03a4cd9f76b0cf269524dce2006acdcfd77d757c929fca6620c883fa5",
    container_type = container_type
  )(
    method = method,
    sd_filter = sd_filter,
    absolute_width = absolute_width,
    width_scale_factor = width_scale_factor,
    outlier_tolerance_factor = outlier_tolerance_factor,
    rooting_method = rooting_method,
    num_topics_lower = num_topics_lower,
    num_topics_upper = num_topics_upper,
    tot_iter = tot_iter,
    tolerance = tolerance
  )
}

