######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using CellTrails
#' 
#' @description
#' Will generate a trajectory using
#' [CellTrails](https://doi.org/10.1016/j.celrep.2018.05.002).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_celltrails).
#' The original code of this method is available
#' [here](https://github.com/dcellwanger/CellTrails).
#' 
#' @references Ellwanger, D.C., Scheibinger, M., Dumont, R.A., Barr-Gillespie,
#' P.G., Heller, S., 2018. Transcriptional Dynamics of Hair-Bundle Morphogenesis
#' Revealed with CellTrails. Cell Reports 23, 2901–2914.e14.
#' 
#' @param filter_features logical; Whether to include celltrails feature filtering
#' @param threshold_dl integer; Minimum number of samples; if value < 1 it is
#' interpreted as fraction, otherwise as absolute sample count (default: `2L`;
#' range: from `0L` to `100L`)
#' @param threshold_cov numeric; Minimum coefficient of variation; numeric value
#' between 0 and 1 (default: `0.05`; range: from `0L` to `1L`)
#' @param threshold_ff numeric; A Z-score cutoff (default: `1.7`; range: from `0L`
#' to `5L`)
#' @param min_expr numeric; Minimum average feature expression (default: `0L`;
#' range: from `0L` to `2L`)
#' @param frac numeric; Fraction or number (if frac > 1) of eigengaps used to
#' perform linear fit. (default: `100L`; range: from `1L` to `1000L`)
#' @param min_size numeric; The initial cluster dedrogram is cut at an height such
#' that the minimum cluster size is at least min_size; if min_size < 1 than the
#' fraction of total samples is used, otherwise it is used as absoulte count
#' (default: `0.01`; range: from `0.001` to `1L`)
#' @param min_feat integer; Minimum number of differentially expressed features
#' between siblings. If this number is not reached, two neighboring clusters
#' (siblings) in the pruned dendrogram get joined. (default: `5L`; range: from
#' `1L` to `100L`)
#' @param max_pval numeric; Maximum P-value for differential expression
#' computation. (default: `1e-04`; range: from `1e-07` to `1L`)
#' @param min_fc numeric; Mimimum fold-change for differential expression
#' computation (default: `2L`; range: from `0L` to `5L`)
#' @param l integer; Neighborhood size (default: `10L`; range: from `1L` to `50L`)
#' @inheritParams dynwrap::create_ti_method_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_celltrails <- function(
    filter_features = FALSE,
    threshold_dl = 2L,
    threshold_cov = 0.05,
    threshold_ff = 1.7,
    min_expr = 0L,
    frac = 100L,
    min_size = 0.01,
    min_feat = 5L,
    max_pval = 1e-04,
    min_fc = 2L,
    l = 10L
) {
  create_ti_method_container(
    container_id = "dynverse/ti_celltrails",
    version = dynmethods::method_versions[["dynverse/ti_celltrails"]],
  )(
    filter_features = filter_features,
    threshold_dl = threshold_dl,
    threshold_cov = threshold_cov,
    threshold_ff = threshold_ff,
    min_expr = min_expr,
    frac = frac,
    min_size = min_size,
    min_feat = min_feat,
    max_pval = max_pval,
    min_fc = min_fc,
    l = l
  )
}

