######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Component 1
#' 
#' @description
#' Will generate a trajectory using Component 1.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_comp1).
#' 
#' 
#' 
#' 
#' @param dimred discrete; Which dimensionality reduction method to use. (default:
#' `"pca"`; values: {`"pca"`, `"mds"`, `"tsne"`, `"ica"`, `"lle"`,
#' `"landmark_mds"`, `"mds_sammon"`, `"mds_isomds"`, `"mds_smacof"`, `"umap"`,
#' `"dm_diffusionMap"`})
#' @param ndim integer; (default: `2L`; range: from `2L` to `30L`)
#' @param component integer; (default: `1L`; range: from `1L` to `10L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_comp1 <- function(
    dimred = "pca",
    ndim = 2L,
    component = 1L
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_comp1",
    version = dynmethods::method_versions[["dynverse/ti_comp1"]],
  )(
    dimred = dimred,
    ndim = ndim,
    component = component
  )
}

