######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Component 1
#' 
#' @description
#' Will generate a trajectory using Component 1.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/comp1).
#' 
#' 
#' 
#' 
#' @param dimred discrete; Which dimensionality reduction method to use. (default:
#' `"pca"`; values: {`"pca"`, `"mds"`, `"tsne"`, `"ica"`, `"lle"`,
#' `"landmark_mds"`, `"mds_sammon"`, `"mds_isomds"`, `"mds_smacof"`, `"umap"`,
#' `"dm_diffusionMap"`})
#' @param ndim integer; (default: `2`; range: from `2` to `30`)
#' @param component integer; (default: `1`; range: from `1` to `10`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_comp1 <- function(
    dimred = "pca",
    ndim = 2,
    component = 1,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/dynmethods:comp1",
    version = method_versions[["dynverse/dynmethods:comp1"]],
    config = config
  )(
    dimred = dimred,
    ndim = ndim,
    component = component
  )
}

