######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using DPT
#' 
#' @description
#' Will generate a trajectory using [DPT](https://doi.org/10.1038/nmeth.3971).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/dpt).
#' The original code of this method is available
#' [here](https://bioconductor.org/packages/release/bioc/html/destiny.html).
#' 
#' @references Haghverdi, L., Büttner, M., Wolf, F.A., Buettner, F., Theis, F.J.,
#' 2016. Diffusion pseudotime robustly reconstructs lineage branching. Nature
#' Methods 13, 845–848.
#' 
#' @param sigma discrete; Diffusion scale parameter of the Gaussian kernel. A
#' larger sigma might be necessary if the eigenvalues can not be found because of
#' a singularity in the matrix. Must be one of:\itemize{\item A character vector:
#' \code{"local"} (default) or \code{"global"},\item a numeric global sigma -- a
#' global sigma will be calculated using
#' \code{\link[destiny:find_sigmas]{destiny::find_sigmas()}}\item or a
#' \code{\link[destiny:Sigmas-class]{destiny::Sigmas-class()}} object.} (default:
#' `"local"`; values: {`"local"`, `"global"`})
#' @param distance discrete; A \code{\link[stats:dist]{stats::dist()}} object, or
#' a character vector specifying which distance metric to use. Allowed
#' measures:\itemize{\item Euclidean distance (default),\item cosine distance
#' (1-corr(c_1, c_2)), or\item rank correlation distance (1-corr(rank(c_1),
#' rank(c_2)))} (default: `"euclidean"`; values: {`"euclidean"`, `"cosine"`,
#' `"rankcor"`})
#' @param ndim integer; Number of eigenvectors/dimensions to return (default:
#' `20L`; range: from `3L` to `100L`)
#' @param density_norm logical; Logical. If TRUE, use density normalisation
#' @param n_local_lower integer; If sigma == 'local', the
#' \code{n_local_lower}:\code{n_local_upper} nearest neighbor(s) determine(s) the
#' local sigma (default: `5L`; range: from `2L` to `20L`)
#' @param n_local_upper integer; See \code{n_local_lower} (default: `7L`; range:
#' from `2L` to `20L`)
#' @param w_width numeric; Window width to use for deciding the branch cutoff
#' (default: `0.1`; range: from `1e-04` to `1`)
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_dpt <- function(
    sigma = "local",
    distance = "euclidean",
    ndim = 20L,
    density_norm = TRUE,
    n_local_lower = 5L,
    n_local_upper = 7L,
    w_width = 0.1,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/dpt",
    run_environment = run_environment,
    sigma = sigma,
    distance = distance,
    ndim = ndim,
    density_norm = density_norm,
    n_local_lower = n_local_lower,
    n_local_upper = n_local_upper,
    w_width = w_width
  )
}

