######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Error
#' 
#' @description
#' Will generate a trajectory using Error.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_error).
#' 
#' 
#' 
#' 
#' @param dummy_param numeric; Dummy parameter (default: `0.5`; range: from `0` to
#' `1`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_error <- function(
    dummy_param = 0.5
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_error",
    version = dynmethods::method_versions[["dynverse/ti_error"]],
  )(
    dummy_param = dummy_param
  )
}

