######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using ElPiGraph
#' 
#' @description
#' Will generate a trajectory using
#' [ElPiGraph](https://github.com/Albluca/ElPiGraph.R).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/elpigraph).
#' The original code of this method is available
#' [here](https://github.com/Albluca/ElPiGraph.R).
#' 
#' 
#' 
#' @param topology discrete; The kind of topology to detect (default: `"tree"`;
#' values: {`"cycle"`, `"tree"`, `"linear"`})
#' @param NumNodes integer; The number of nodes of the principal graph (default:
#' `50L`; range: from `2L` to `1000L`)
#' @param NumEdges integer; The maximum number of edges (default: `100000L`;
#' range: from `2L` to `100000L`)
#' @param InitNodes integer; Number of points to include in the initial graph
#' (default: `2L`; range: from `2L` to `1000L`)
#' @param Mu numeric; Controls the elastic energy (default: `0.1`; range: from
#' `0.001` to `1L`)
#' @param Lambda numeric; Controls the elastic energy (default: `0.01`; range:
#' from `0.001` to `1L`)
#' @param MaxNumberOfIterations integer; Maximum number of steps to embed the
#' nodes (default: `10L`; range: from `1L` to `1000L`)
#' @param eps numeric; Minimal relative change in the position of the nodes to
#' stop embedment (default: `0.01`; range: from `0.001` to `1L`)
#' @param CenterData logical; Should data and initial node positions be centered?
#' @inheritParams create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_elpigraph <- function(
    topology = "tree",
    NumNodes = 50L,
    NumEdges = 100000L,
    InitNodes = 2L,
    Mu = 0.1,
    Lambda = 0.01,
    MaxNumberOfIterations = 10L,
    eps = 0.01,
    CenterData = FALSE,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/elpigraph",
    run_environment = run_environment,
    topology = topology,
    NumNodes = NumNodes,
    NumEdges = NumEdges,
    InitNodes = InitNodes,
    Mu = Mu,
    Lambda = Lambda,
    MaxNumberOfIterations = MaxNumberOfIterations,
    eps = eps,
    CenterData = CenterData
  )
}

