######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Control: error
#' 
#' @description
#' Will generate a trajectory using Control: error.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/error).
#' 
#' 
#' 
#' 
#' @param dummy_param numeric; Dummy parameter (default: `0.5`; range: from `0` to
#' `1`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_error <- function(
    dummy_param = 0.5,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = repo_digests[["dynverse/error"]],
    config = config
  )(
    dummy_param = dummy_param
  )
}

