######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using FORKS
#' 
#' @description
#' Will generate a trajectory using [FORKS](https://doi.org/10.1101/132811).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/forks).
#' The original code of this method is available
#' [here](https://github.com/macsharma/FORKS).
#' 
#' @references Sharma, M., Li, H., Sengupta, D., Prabhakar, S., Jayadeva, J.,
#' 2017. FORKS: Finding Orderings Robustly using K-means and Steiner trees.
#' 
#' @param norm_function discrete; No description provided by the author. (default:
#' `"median"`; values: {`"mean"`, `"median"`, `"quantile"`})
#' @param norm_quantile numeric; No description provided by the author. (default:
#' `75L`; range: from `0L` to `100L`)
#' @param cum_sum_exp_var numeric; No description provided by the author.
#' (default: `0.9`; range: from `0` to `1`)
#' @param min_cluster integer; No description provided by the author. (default:
#' `4L`; range: from `3L` to `20L`)
#' @param max_cluster integer; No description provided by the author. (default:
#' `10L`; range: from `3L` to `20L`)
#' @param mapping_type discrete; No description provided by the author. (default:
#' `"Isomap"`; values: {`"Isomap"`, `"MDS"`, `"PCA"`, `"RandomForest"`,
#' `"SpectralEmbedding"`, `"LLE_standard"`, `"tSNE"`})
#' @param initialization discrete; No description provided by the author.
#' (default: `"kmeans"`; values: {`"kmeans"`, `"kmedoids"`, `"random"`})
#' @param iterMax integer; No description provided by the author. (default:
#' `1000L`; range: from `100L` to `100000L`)
#' @param eta numeric; No description provided by the author. (default: `0.01`;
#' range: from `1e-04` to `100L`)
#' @param C numeric; No description provided by the author. (default: `1L`; range:
#' from `1e-04` to `1000L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_forks <- function(
    norm_function = "median",
    norm_quantile = 75L,
    cum_sum_exp_var = 0.9,
    min_cluster = 4L,
    max_cluster = 10L,
    mapping_type = "Isomap",
    initialization = "kmeans",
    iterMax = 1000L,
    eta = 0.01,
    C = 1L,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/forks@sha256:c0fa64d4f280b608210d05fa74d9577db444855a60c6a9d93b0936fa0eb7623d",
    container_type = container_type
  )(
    norm_function = norm_function,
    norm_quantile = norm_quantile,
    cum_sum_exp_var = cum_sum_exp_var,
    min_cluster = min_cluster,
    max_cluster = max_cluster,
    mapping_type = mapping_type,
    initialization = initialization,
    iterMax = iterMax,
    eta = eta,
    C = C
  )
}

