######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using GNG
#' 
#' @description
#' Will generate a trajectory using [GNG](https://github.com/rcannood/gng).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_gng).
#' The original code of this method is available
#' [here](https://github.com/rcannood/gng).
#' 
#' 
#' 
#' @param dimred discrete; Which dimensionality reduction method to use. (default:
#' `"pca"`; values: {`"pca"`, `"mds"`, `"tsne"`, `"ica"`, `"lle"`,
#' `"landmark_mds"`, `"mds_sammon"`, `"mds_isomds"`, `"mds_smacof"`, `"umap"`,
#' `"dm_diffusionMap"`})
#' @param ndim integer; The number of dimensions (default: `5L`; range: from `2L`
#' to `10L`)
#' @param max_iter numeric; The max number of iterations (default: `15000`; range:
#' from `25` to `1e+06`)
#' @param max_nodes integer; The maximum number of nodes (default: `8L`; range:
#' from `2L` to `30L`)
#' @param apply_mst logical; If true, an MST post-processing of the GNG is
#' performed.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_gng <- function(
    dimred = "pca",
    ndim = 5L,
    max_iter = 15000,
    max_nodes = 8L,
    apply_mst = TRUE
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_gng",
    version = dynmethods::method_versions[["dynverse/ti_gng"]],
  )(
    dimred = dimred,
    ndim = ndim,
    max_iter = max_iter,
    max_nodes = max_nodes,
    apply_mst = apply_mst
  )
}

