######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using GPfates
#' 
#' @description
#' Will generate a trajectory using
#' [GPfates](https://doi.org/10.1126/sciimmunol.aal2192).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/gpfates).
#' The original code of this method is available
#' [here](https://github.com/Teichlab/GPfates).
#' 
#' @references Lönnberg, T., Svensson, V., James, K.R., Fernandez-Ruiz, D.,
#' Sebina, I., Montandon, R., Soon, M.S.F., Fogg, L.G., Nair, A.S., Liligeto,
#' U.N., Stubbington, M.J.T., Ly, L.-H., Bagger, F.O., Zwiessele, M., Lawrence,
#' N.D., Souza-Fonseca-Guimaraes, F., Bunn, P.T., Engwerda, C.R., Heath, W.R.,
#' Billker, O., Stegle, O., Haque, A., Teichmann, S.A., 2017. Single-cell RNA-seq
#' and computational analysis using temporal mixture modeling resolves TH1/TFHfate
#' bifurcation in malaria. Science Immunology 2, eaal2192.
#' 
#' @param log_expression_cutoff numeric; The log expression cutoff (default:
#' `0.5`; range: from `0.5` to `5L`)
#' @param min_cells_expression_cutoff numeric; The min expression cutoff (default:
#' `0L`; range: from `0L` to `20L`)
#' @param ndim integer; Number of dimensions for dimensionality reduction
#' (default: `2L`; range: from `1L` to `5L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_gpfates <- function(
    log_expression_cutoff = 0.5,
    min_cells_expression_cutoff = 0L,
    ndim = 2L,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = repo_digests[["dynverse/gpfates"]],
    config = config
  )(
    log_expression_cutoff = log_expression_cutoff,
    min_cells_expression_cutoff = min_cells_expression_cutoff,
    ndim = ndim
  )
}

