######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using GrandPrix
#' 
#' @description
#' Will generate a trajectory using [GrandPrix](https://doi.org/10.1101/227843).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_grandprix).
#' The original code of this method is available
#' [here](https://github.com/ManchesterBioinference/GrandPrix).
#' 
#' @references Ahmed, S., Rattray, M., Boukouvalas, A., 2017. GrandPrix: Scaling
#' up the Bayesian GPLVM for single-cell data.
#' 
#' @param n_inducing_points integer; (default: `40L`; range: from `10L` to `500L`)
#' @param latent_prior_var numeric; (default: `0.1`; range: from `NULL` to `NULL`)
#' @param latent_var numeric; (default: `0.028`; range: from `NULL` to `NULL`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_grandprix <- function(
    n_inducing_points = 40L,
    latent_prior_var = 0.1,
    latent_var = 0.028
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_grandprix",
    version = dynmethods::method_versions[["dynverse/ti_grandprix"]],
  )(
    n_inducing_points = n_inducing_points,
    latent_prior_var = latent_prior_var,
    latent_var = latent_var
  )
}

