######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Control: identity
#' 
#' @description
#' Will generate a trajectory using Control: identity.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/identity).
#' 
#' 
#' 
#' 
#' @param dummy_param numeric; Dummy parameter (default: `0.5`; range: from `0` to
#' `1`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_identity <- function(
    dummy_param = 0.5,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/identity@sha256:ca86db63d0f703f6502cb18f824ffb24ae4bb9755675e9a0a545486746ec9523",
    container_type = container_type
  )(
    dummy_param = dummy_param
  )
}

