######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Monocle ICA
#' 
#' @description
#' Will generate a trajectory using [Monocle
#' ICA](https://doi.org/10.1038/nmeth.4402).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/monocle_ica).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' @references Qiu, X., Mao, Q., Tang, Y., Wang, L., Chawla, R., Pliner, H.A.,
#' Trapnell, C., 2017. Reversed graph embedding resolves complex single-cell
#' trajectories. Nature Methods 14, 979–982.
#' 
#' @param reduction_method discrete; A character string specifying the algorithm
#' to use for dimensionality reduction. (default: `"ICA"`; values: {`"ICA"`})
#' @param max_components integer; The dimensionality of the reduced space
#' (default: `2L`; range: from `2L` to `20L`)
#' @param norm_method discrete; Determines how to transform expression values
#' prior to reducing dimensionality (default: `"log"`; values: {`"vstExprs"`,
#' `"log"`, `"none"`})
#' @param filter_features logical; Whether to include monocle feature filtering
#' @param filter_features_mean_expression numeric; Minimal mean feature
#' expression, only used when `filter_features` is set to TRUE (default: `0.1`;
#' range: from `0L` to `10L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_monocle_ica <- function(
    reduction_method = "ICA",
    max_components = 2L,
    norm_method = "log",
    filter_features = TRUE,
    filter_features_mean_expression = 0.1,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = repo_digests[["dynverse/monocle_ica"]],
    config = config
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method,
    filter_features = filter_features,
    filter_features_mean_expression = filter_features_mean_expression
  )
}

