######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using mfa
#' 
#' @description
#' Will generate a trajectory using
#' [mfa](https://doi.org/10.12688/wellcomeopenres.11087.1).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/mfa).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/mfa).
#' 
#' @references Campbell, K.R., Yau, C., 2017. Probabilistic modeling of
#' bifurcations in single-cell gene expression data using a Bayesian mixture of
#' factor analyzers. Wellcome Open Research 2, 19.
#' 
#' @param b integer; Number of branches to model (default: `2L`; range: from `1L`
#' to `10L`)
#' @param iter integer; Number of MCMC iterations (default: `2000L`; range: from
#' `20L` to `5000L`)
#' @param thin integer; MCMC samples to thin (default: `1L`; range: from `1L` to
#' `20L`)
#' @param pc_initialise integer; Which principal component to initialise
#' pseudotimes to (default: `1L`; range: from `1L` to `5L`)
#' @param prop_collapse numeric; Proportion of Gibbs samples which should
#' marginalise over c (default: `0`; range: from `0` to `1`)
#' @param scale_input logical; Logical. If true, input is scaled to have mean 0
#' variance 1
#' @param zero_inflation logical; Logical, should zero inflation be enabled?
#' @inheritParams create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_mfa <- function(
    b = 2L,
    iter = 2000L,
    thin = 1L,
    pc_initialise = 1L,
    prop_collapse = 0,
    scale_input = TRUE,
    zero_inflation = FALSE,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/mfa",
    run_environment = run_environment,
    b = b,
    iter = iter,
    thin = thin,
    pc_initialise = pc_initialise,
    prop_collapse = prop_collapse,
    scale_input = scale_input,
    zero_inflation = zero_inflation
  )
}

