######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Monocle DDRTree
#' 
#' @description
#' Will generate a trajectory using [Monocle
#' DDRTree](https://doi.org/10.1038/nmeth.4402).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/monocle_ddrtree).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' @references Qiu, X., Mao, Q., Tang, Y., Wang, L., Chawla, R., Pliner, H.A.,
#' Trapnell, C., 2017. Reversed graph embedding resolves complex single-cell
#' trajectories. Nature Methods 14, 979–982.
#' 
#' @param reduction_method discrete; A character string specifying the algorithm
#' to use for dimensionality reduction. (default: `"DDRTree"`; values:
#' {`"DDRTree"`})
#' @param max_components integer; The dimensionality of the reduced space
#' (default: `2L`; range: from `2L` to `20L`)
#' @param norm_method discrete; Determines how to transform expression values
#' prior to reducing dimensionality (default: `"vstExprs"`; values: {`"vstExprs"`,
#' `"log"`, `"none"`})
#' @param auto_param_selection logical; When this argument is set to TRUE
#' (default), it will automatically calculate the proper value for the ncenter
#' (number of centroids) parameters which will be passed into DDRTree call.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_monocle_ddrtree <- function(
    reduction_method = "DDRTree",
    max_components = 2L,
    norm_method = "vstExprs",
    auto_param_selection = TRUE,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/monocle_ddrtree@sha256:a4721dded3f254e09ecd57eec7fad3f2f7e6f03065d4ddbf76aedbf79c62fa5a",
    container_type = container_type
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method,
    auto_param_selection = auto_param_selection
  )
}

