######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using MERLoT
#' 
#' @description
#' Will generate a trajectory using [MERLoT](https://doi.org/10.1101/261768).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/merlot).
#' The original code of this method is available
#' [here](https://github.com/soedinglab/merlot).
#' 
#' @references Parra, R.G., Papadopoulos, N., Ahumada-Arranz, L., El Kholtei, J.,
#' Treutlein, B., Soeding, J., 2018. Reconstructing complex lineage trees from
#' scRNA-seq data using MERLoT.
#' 
#' @param sigma discrete; Diffusion scale parameter of the Gaussian kernel. A
#' larger sigma might be necessary if the eigenvalues can not be found because of
#' a singularity in the matrix. Must be one of:\itemize{\item A character vector:
#' \code{"local"} (default) or \code{"global"},\item a numeric global sigma -- a
#' global sigma will be calculated using
#' \code{\link[destiny:find_sigmas]{destiny::find_sigmas()}}\item or a
#' \code{\link[destiny:Sigmas-class]{destiny::Sigmas-class()}} object.} (default:
#' `"local"`; values: {`"local"`, `"global"`})
#' @param distance discrete; A \code{\link[stats:dist]{stats::dist()}} object, or
#' a character vector specifying which distance metric to use. Allowed
#' measures:\itemize{\item Euclidean distance (default),\item cosine distance
#' (1-corr(c_1, c_2)), or\item rank correlation distance (1-corr(rank(c_1),
#' rank(c_2)))} (default: `"euclidean"`; values: {`"euclidean"`, `"cosine"`,
#' `"rankcor"`})
#' @param ndim integer; Number of eigenvectors/dimensions to return (default:
#' `20L`; range: from `2L` to `20L`)
#' @param density_norm logical; Logical. If TRUE, use density normalisation
#' @param n_local_lower integer; If sigma == 'local', the
#' \code{n_local_lower}:\code{n_local_upper} nearest neighbor(s) determine(s) the
#' local sigma (default: `5L`; range: from `2L` to `20L`)
#' @param n_local_upper integer; See \code{n_local_lower} (default: `7L`; range:
#' from `2L` to `20L`)
#' @param w_width numeric; Window width to use for deciding the branch cutoff
#' (default: `0.01`; range: from `1e-04` to `1`)
#' @param n_components_to_use integer; Which components to use in downstream
#' analysis (default: `3`; range: from `2` to `20`)
#' @param N_yk integer; Number of nodes for the elastic principal tree (default:
#' `100`; range: from `2` to `1000`)
#' @param lambda_0 numeric; Principal elastic tree energy function parameter.
#' (default: `8e-10`; range: from `1e-12` to `1e-06`)
#' @param mu_0 numeric; Principal elastic tree energy function parameter.
#' (default: `0.0025`; range: from `5e-04` to `0.005`)
#' @param increaseFactor_mu numeric; Factor by which the mu will be increased for
#' the embedding (default: `20`; range: from `2` to `50`)
#' @param increaseFactor_lambda numeric; Factor by which the mu will be increased
#' for the embedding (default: `20`; range: from `2` to `50`)
#' @param FixEndpoints logical; Documentation not provided by authors
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_merlot <- function(
    sigma = "local",
    distance = "euclidean",
    ndim = 20L,
    density_norm = TRUE,
    n_local_lower = 5L,
    n_local_upper = 7L,
    w_width = 0.01,
    n_components_to_use = 3,
    N_yk = 100,
    lambda_0 = 8e-10,
    mu_0 = 0.0025,
    increaseFactor_mu = 20,
    increaseFactor_lambda = 20,
    FixEndpoints = FALSE,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/merlot@sha256:745ecb038c3c0138bc76cdb50e23dea049f7ae675aa4c7868dfcbaefd41edc40",
    config = config
  )(
    sigma = sigma,
    distance = distance,
    ndim = ndim,
    density_norm = density_norm,
    n_local_lower = n_local_lower,
    n_local_upper = n_local_upper,
    w_width = w_width,
    n_components_to_use = n_components_to_use,
    N_yk = N_yk,
    lambda_0 = lambda_0,
    mu_0 = mu_0,
    increaseFactor_mu = increaseFactor_mu,
    increaseFactor_lambda = increaseFactor_lambda,
    FixEndpoints = FixEndpoints
  )
}

