######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title MST
#' 
#' @description
#' Will generate a trajectory using MST.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_mst).
#' 
#' 
#' 
#' 
#' @param dimred Which dimensionality reduction method to use. Domain: {pca, mds,
#' tsne, ica, lle, landmark_mds, mds_sammon, mds_isomds, mds_smacof, umap,
#' dm_diffusionMap}. Default: pca. Format: character.
#' @param ndim . Domain: U(2, 30). Default: 2. Format: integer.
#' 
#' @keywords method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_mst <- function(
    dimred = "pca",
    ndim = 2L
) {
  create_ti_method_container(
    container_id = "dynverse/ti_mst:v0.9.9",
  )(
    dimred = dimred,
    ndim = ndim
  )
}

