######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Monocle ICA
#' 
#' @description
#' Will generate a trajectory using [Monocle
#' ICA](https://doi.org/10.1038/nmeth.4402).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/monocle_ica).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' @references Qiu, X., Mao, Q., Tang, Y., Wang, L., Chawla, R., Pliner, H.A.,
#' Trapnell, C., 2017. Reversed graph embedding resolves complex single-cell
#' trajectories. Nature Methods 14, 979–982.
#' 
#' @param reduction_method discrete; A character string specifying the algorithm
#' to use for dimensionality reduction. (default: `"ICA"`; values: {`"ICA"`})
#' @param max_components integer; The dimensionality of the reduced space
#' (default: `2L`; range: from `2L` to `20L`)
#' @param norm_method discrete; Determines how to transform expression values
#' prior to reducing dimensionality (default: `"vstExprs"`; values: {`"vstExprs"`,
#' `"log"`, `"none"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_monocle_ica <- function(
    reduction_method = "ICA",
    max_components = 2L,
    norm_method = "vstExprs",
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/monocle_ica@sha256:127a12e349192d3cbf90e554c9f6ce60293ade0ed15e8adef0defa5328888f95",
    container_type = container_type
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method
  )
}

