######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using MATCHER
#' 
#' @description
#' Will generate a trajectory using
#' [MATCHER](https://doi.org/10.1186/s13059-017-1269-0).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_matcher).
#' The original code of this method is available
#' [here](https://github.com/jw156605/MATCHER).
#' 
#' @references Welch, J.D., Hartemink, A.J., Prins, J.F., 2017. MATCHER: manifold
#' alignment reveals correspondence between single cell transcriptome and
#' epigenome dynamics. Genome Biology 18.
#' 
#' @param quantiles integer; Quantiles How many quantiles to use when computing
#' warp functions (integer) (default: `50L`; range: from `2L` to `500L`)
#' @param method discrete; Gaussian process regression or linear interpolation?
#' ("gp" or "linear) (default: `"linear"`; values: {`"gp"`, `"linear"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_matcher <- function(
    quantiles = 50L,
    method = "linear",
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/ti_matcher",
    version = method_versions[["dynverse/ti_matcher"]],
    config = config
  )(
    quantiles = quantiles,
    method = method
  )
}

