######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Monocle ICA
#' 
#' @description
#' Will generate a trajectory using [Monocle
#' ICA](https://doi.org/10.1038/nmeth.4402).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_monocle_ica).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' @references Qiu, X., Mao, Q., Tang, Y., Wang, L., Chawla, R., Pliner, H.A.,
#' Trapnell, C., 2017. Reversed graph embedding resolves complex single-cell
#' trajectories. Nature Methods 14, 979–982.
#' 
#' @param reduction_method Parameter; A character string specifying the algorithm
#' to use for dimensionality reduction., Domain: {ICA}, Default: ICA, Format:
#' character.
#' @param max_components Parameter; The dimensionality of the reduced space.,
#' Domain: U(2, 20), Default: 2, Format: integer.
#' @param norm_method Parameter; Determines how to transform expression values
#' prior to reducing dimensionality., Domain: {vstExprs, log, none}, Default: log,
#' Format: character.
#' @param filter_features Parameter; Whether to include monocle feature
#' filtering., Default: TRUE, Format: logical.
#' @param filter_features_mean_expression Parameter; Minimal mean feature
#' expression, only used when `filter_features` is set to TRUE., Domain: U(0, 10),
#' Default: 0.1, Format: numeric.
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_monocle_ica <- function(
    reduction_method = "ICA",
    max_components = 2L,
    norm_method = "log",
    filter_features = TRUE,
    filter_features_mean_expression = 0.1
) {
  create_ti_method_container(
    container_id = "dynverse/ti_monocle_ica:v0.9.9",
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method,
    filter_features = filter_features,
    filter_features_mean_expression = filter_features_mean_expression
  )
}

