######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Mpath
#' 
#' @description
#' Will generate a trajectory using [Mpath](https://doi.org/10.1038/ncomms11988).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/mpath).
#' The original code of this method is available
#' [here](https://github.com/JinmiaoChenLab/Mpath).
#' 
#' @references Chen, J., Schlitzer, A., Chakarov, S., Ginhoux, F., Poidinger, M.,
#' 2016. Mpath maps multi-branching single-cell trajectories revealing progenitor
#' cell progression during development. Nature Communications 7, 11988.
#' 
#' @param distMethod discrete; The method for calculating dissimilarity between
#' cells. distMethod can be one of "pearson", "kendall", "spearman" or
#' "euclidean". Default is "euclidean". (default: `"euclidean"`; values:
#' {`"pearson"`, `"kendall"`, `"spearman"`, `"euclidean"`})
#' @param method discrete; Method for distinguishing landmark clusters from
#' non-landmark clusters.method can be "kmeans" or "diversity" or "size" or
#' "diversity_size". When method="diversity", numlm needs to be specified. Default
#' is "diversity_size". (default: `"kmeans"`; values: {`"kmeans"`, `"diversity"`,
#' `"size"`, `"diversity_size"`})
#' @param numcluster integer; Number of initial clusters (default: `11L`; range:
#' from `3L` to `30L`)
#' @param numcluster_null logical; If TRUE, will automatically select the number
#' of clusters
#' @param diversity_cut numeric; The cutoff value of diversity for differentiating
#' landmark clusters from non-landmark clusters. The diversity of a landmark
#' cluster must be below this cutoff. (default: `0.6`; range: from `0.1` to `1`)
#' @param size_cut numeric; The cutoff value of size i.e. number of cells for
#' differentiating landmark clusters from non-landmark clusters. The number of
#' cells in a landmark cluster must be greater than this cutoff. (default: `0.05`;
#' range: from `0.01` to `1`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_mpath <- function(
    distMethod = "euclidean",
    method = "kmeans",
    numcluster = 11L,
    numcluster_null = TRUE,
    diversity_cut = 0.6,
    size_cut = 0.05,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/dynmethods:mpath",
    version = method_versions[["dynverse/dynmethods:mpath"]],
    config = config
  )(
    distMethod = distMethod,
    method = method,
    numcluster = numcluster,
    numcluster_null = numcluster_null,
    diversity_cut = diversity_cut,
    size_cut = size_cut
  )
}

