######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using ouijaflow
#' 
#' @description
#' Will generate a trajectory using [ouijaflow](https://doi.org/10.1101/060442).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_ouijaflow).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/ouija).
#' 
#' @references Campbell, K.R., Yau, C., 2016. A descriptive marker gene approach
#' to single-cell pseudotime inference.
#' 
#' @param iter integer; (default: `1000L`; range: from `2L` to `50000L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_ouijaflow <- function(
    iter = 1000L
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_ouijaflow",
    version = dynmethods::method_versions[["dynverse/ti_ouijaflow"]],
  )(
    iter = iter
  )
}

