######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using ouijaflow
#' 
#' @description
#' Will generate a trajectory using [ouijaflow](https://doi.org/10.1101/060442).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/ouijaflow).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/ouija).
#' 
#' @references Campbell, K.R., Yau, C., 2016. A descriptive marker gene approach
#' to single-cell pseudotime inference.
#' 
#' @param iter integer; (default: `1000L`; range: from `2L` to `50000L`)
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_ouijaflow <- function(
    iter = 1000L,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/ouijaflow",
    run_environment = run_environment,
    iter = iter
  )
}

