######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using ouija
#' 
#' @description
#' Will generate a trajectory using [ouija](https://doi.org/10.1101/060442).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/ouija).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/ouija).
#' 
#' @references Campbell, K.R., Yau, C., 2016. A descriptive marker gene approach
#' to single-cell pseudotime inference.
#' 
#' @param iter numeric; Number of iterations (default: `100L`; range: from `10L`
#' to `1000L`)
#' @param response_type discrete; A vector declaring whether each gene exhibits
#' "switch" or "transient"expression. Defaults to "switch" for all genes (default:
#' `"switch"`; values: {`"switch"`, `"transient"`})
#' @param inference_type discrete; The type of inference to be performed, either
#' \code{hmc} for HamiltonianMonte Carlo or \code{vb} for ADVI (Variational
#' Bayes). Note that HMC is typically more accuratebut VB will be orders of
#' magnitude faster. (default: `"hmc"`; values: {`"hmc"`, `"vb"`})
#' @param normalise_expression logical; Logical, default TRUE. If TRUE the data is
#' pre-normalisedso the average peak expression is approximately 1. This makes the
#' strength parametersapproximately comparable between genes.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_ouija <- function(
    iter = 100L,
    response_type = "switch",
    inference_type = "hmc",
    normalise_expression = TRUE,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/dynmethods:ouija",
    version = method_versions[["dynverse/dynmethods:ouija"]],
    config = config
  )(
    iter = iter,
    response_type = response_type,
    inference_type = inference_type,
    normalise_expression = normalise_expression
  )
}

