######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Periodic PrinCurve
#' 
#' @description
#' Will generate a trajectory using Periodic PrinCurve.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/periodpc).
#' 
#' 
#' 
#' 
#' @param ndim integer; (default: `3`; range: from `2` to `10`)
#' @param maxit integer; (default: `10`; range: from `0` to `100`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_periodpc <- function(
    ndim = 3,
    maxit = 10,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/periodpc@sha256:dd828c576e1e1002b4fca5fcd739cd1b5b9c4bd8f175bc4e08a4bdc872b0312b",
    config = config
  )(
    ndim = ndim,
    maxit = maxit
  )
}

