######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using PAGA Projected
#' 
#' @description
#' Will generate a trajectory using [PAGA
#' Projected](https://doi.org/10.1101/208819).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/paga_projected).
#' The original code of this method is available
#' [here](https://github.com/theislab/graph_abstraction).
#' 
#' @references Wolf, F.A., Hamey, F., Plass, M., Solana, J., Dahlin, J.S.,
#' Gottgens, B., Rajewsky, N., Simon, L., Theis, F.J., 2017. Graph abstraction
#' reconciles clustering with trajectory inference through a topology preserving
#' map of single cells.
#' 
#' @param n_neighbors integer; Number of neighbours for knn (default: `30L`;
#' range: from `1L` to `100L`)
#' @param n_comps integer; Number of principal components (default: `50L`; range:
#' from `0L` to `100L`)
#' @param n_dcs integer; Number of diffusion components for denoising graph, 0
#' means no denoising. (default: `15L`; range: from `0L` to `40L`)
#' @param resolution numeric; Resolution of louvain clustering, which determines
#' the granularity of the clustering. Higher values will result in more clusters.
#' (default: `2.5`; range: from `0.1` to `10L`)
#' @param embedding_type discrete; Either 'umap' (scales very well, recommended
#' for very large datasets) or 'fa' (ForceAtlas2, often a bit more intuitive for
#' small datasets). (default: `"fa"`; values: {``})
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_paga_projected <- function(
    n_neighbors = 30L,
    n_comps = 50L,
    n_dcs = 15L,
    resolution = 2.5,
    embedding_type = "fa",
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/paga_projected",
    run_environment = run_environment,
    n_neighbors = n_neighbors,
    n_comps = n_comps,
    n_dcs = n_dcs,
    resolution = resolution,
    embedding_type = embedding_type
  )
}

