######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using PhenoPath
#' 
#' @description
#' Will generate a trajectory using [PhenoPath](https://doi.org/10.1101/159913).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_phenopath).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/phenopath).
#' 
#' @references Campbell, K., Yau, C., 2017. Uncovering genomic trajectories with
#' heterogeneous genetic and environmental backgrounds across single-cells and
#' populations.
#' 
#' @param thin integer; The number of iterations to wait each time
#' beforere-calculating the elbo (default: `40L`; range: from `2L` to `500L`)
#' @param z_init discrete; The initialisation of the latent trajectory. Should be
#' one of\enumerate{\item A positive integer describing which principal component
#' of the data shouldbe used for initialisation (default 1), \emph{or}\item A
#' numeric vector of length number of samples to be used directly for
#' initialisation, \emph{or}\item The text character \code{"random"}, for random
#' initialisation from a standard normal distribution.} (default: `"1"`; values:
#' {`"1"`, `"2"`, `"3"`, `"4"`, `"5"`, `"random"`})
#' @param model_mu logical; Logical - should a gene-specific intercept term be
#' modelled?
#' @param scale_y logical; Logical - should the expression matrix be centre
#' scaled?
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_phenopath <- function(
    thin = 40L,
    z_init = "1",
    model_mu = FALSE,
    scale_y = TRUE,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/ti_phenopath",
    version = dynmethods::method_versions[["dynverse/ti_phenopath"]],
    config = config
  )(
    thin = thin,
    z_init = z_init,
    model_mu = model_mu,
    scale_y = scale_y
  )
}

