######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Projected TSCAN
#' 
#' @description
#' Will generate a trajectory using Projected TSCAN.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/projected_tscan).
#' 
#' 
#' 
#' 
#' @param minexpr_percent numeric; (default: `0`; range: from `0` to `1`)
#' @param minexpr_value numeric; (default: `0`; range: from `0` to `10`)
#' @param cvcutoff numeric; (default: `0`; range: from `0` to `5`)
#' @param clusternum_lower integer; (default: `2L`; range: from `2L` to `20L`)
#' @param clusternum_upper integer; (default: `9L`; range: from `2L` to `20L`)
#' @param modelNames discrete; (default: `"VVV"`; values: {`"EII"`, `"VII"`,
#' `"EEI"`, `"VEI"`, `"EVI"`, `"VVI"`, `"EEE"`, `"EVE"`, `"VEE"`, `"VVE"`,
#' `"EEV"`, `"VEV"`, `"EVV"`, `"VVV"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_projected_tscan <- function(
    minexpr_percent = 0,
    minexpr_value = 0,
    cvcutoff = 0,
    clusternum_lower = 2L,
    clusternum_upper = 9L,
    modelNames = "VVV",
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/projected_tscan@sha256:ef776409c2133b02354a39f43ca4200489f638d73f3c4099afcbd8f6c35b5ab7",
    container_type = container_type
  )(
    minexpr_percent = minexpr_percent,
    minexpr_value = minexpr_value,
    cvcutoff = cvcutoff,
    clusternum_lower = clusternum_lower,
    clusternum_upper = clusternum_upper,
    modelNames = modelNames
  )
}

