######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using pCreode
#' 
#' @description
#' Will generate a trajectory using
#' [pCreode](https://doi.org/10.1016/j.cels.2017.10.012).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/pcreode).
#' The original code of this method is available
#' [here](https://github.com/KenLauLab/pCreode).
#' 
#' @references Herring, C.A., Banerjee, A., McKinley, E.T., Simmons, A.J., Ping,
#' J., Roland, J.T., Franklin, J.L., Liu, Q., Gerdes, M.J., Coffey, R.J., Lau,
#' K.S., 2018. Unsupervised Trajectory Analysis of Single-Cell RNA-Seq and Imaging
#' Data Reveals Alternative Tuft Cell Origins in the Gut. Cell Systems 6,
#' 37–51.e9.
#' 
#' @param n_pca_components integer; (default: `3L`; range: from `2L` to `10L`)
#' @param noise numeric; (default: `8L`; range: from `1L` to `20L`)
#' @param num_runs integer; (default: `10L`; range: from `10L` to `100L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_pcreode <- function(
    n_pca_components = 3L,
    noise = 8L,
    num_runs = 10L,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/pcreode@sha256:2920c842b5c35f398e0cecb74ad603a21923d502cf05dc297babab607be59b0f",
    container_type = container_type
  )(
    n_pca_components = n_pca_components,
    noise = noise,
    num_runs = num_runs
  )
}

