######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Periodic PrinCurve
#' 
#' @description
#' Will generate a trajectory using Periodic PrinCurve.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/periodpc).
#' 
#' 
#' 
#' 
#' @param ndim integer; (default: `3`; range: from `2` to `10`)
#' @param maxit integer; (default: `10`; range: from `0` to `100`)
#' @inheritParams create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_periodpc <- function(
    ndim = 3,
    maxit = 10,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/periodpc",
    run_environment = run_environment,
    ndim = ndim,
    maxit = maxit
  )
}

