######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Projected Monocle
#' 
#' @description
#' Will generate a trajectory using [Projected
#' Monocle](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_projected_monocle).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' 
#' 
#' @param reduction_method A character string specifying the algorithm to use for
#' dimensionality reduction. Domain: {DDRTree}. Default: DDRTree. Format:
#' character.
#' @param max_components The dimensionality of the reduced space. Domain: U(2,
#' 20). Default: 2. Format: integer.
#' @param norm_method Determines how to transform expression values prior to
#' reducing dimensionality. Domain: {vstExprs, log, none}. Default: vstExprs.
#' Format: character.
#' @param auto_param_selection When this argument is set to TRUE (default), it
#' will automatically calculate the proper value for the ncenter (number of
#' centroids) parameters which will be passed into DDRTree call. Default: TRUE.
#' Format: logical.
#' @param filter_features Whether to include monocle feature filtering. Default:
#' TRUE. Format: logical.
#' @param filter_features_mean_expression Minimal mean feature expression, only
#' used when `filter_features` is set to TRUE. Domain: U(0, 10). Default: 0.1.
#' Format: numeric.
#' 
#' @keywords method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_projected_monocle <- function(
    reduction_method = "DDRTree",
    max_components = 2L,
    norm_method = "vstExprs",
    auto_param_selection = TRUE,
    filter_features = TRUE,
    filter_features_mean_expression = 0.1
) {
  method_choose_backend(
    package_repository = NULL,
    package_name = NULL,
    function_name = NULL,
    container_id = "dynverse/ti_projected_monocle:v0.9.9.01"
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method,
    auto_param_selection = auto_param_selection,
    filter_features = filter_features,
    filter_features_mean_expression = filter_features_mean_expression
  )
}

