######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using pCreode
#' 
#' @description
#' Will generate a trajectory using
#' [pCreode](https://doi.org/10.1016/j.cels.2017.10.012).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/pcreode).
#' The original code of this method is available
#' [here](https://github.com/KenLauLab/pCreode).
#' 
#' @references Herring, C.A., Banerjee, A., McKinley, E.T., Simmons, A.J., Ping,
#' J., Roland, J.T., Franklin, J.L., Liu, Q., Gerdes, M.J., Coffey, R.J., Lau,
#' K.S., 2018. Unsupervised Trajectory Analysis of Single-Cell RNA-Seq and Imaging
#' Data Reveals Alternative Tuft Cell Origins in the Gut. Cell Systems 6,
#' 37–51.e9.
#' 
#' @param n_pca_components integer; (default: `3L`; range: from `2L` to `10L`)
#' @param radius numeric; (default: `1L`; range: from `0.01` to `10L`)
#' @param noise numeric; (default: `8L`; range: from `1L` to `20L`)
#' @param target numeric; (default: `25L`; range: from `5L` to `100L`)
#' @param num_runs integer; (default: `10L`; range: from `10L` to `1000L`)
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_pcreode <- function(
    n_pca_components = 3L,
    radius = 1L,
    noise = 8L,
    target = 25L,
    num_runs = 10L,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/pcreode",
    run_environment = run_environment,
    n_pca_components = n_pca_components,
    radius = radius,
    noise = noise,
    target = target,
    num_runs = num_runs
  )
}

