######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Periodic PrinCurve
#' 
#' @description
#' Will generate a trajectory using Periodic PrinCurve.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_periodpc).
#' 
#' 
#' 
#' 
#' @param ndim integer; (default: `3`; range: from `2` to `10`)
#' @param maxit integer; (default: `10`; range: from `0` to `100`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_periodpc <- function(
    ndim = 3,
    maxit = 10
) {
  create_ti_method_with_container(
    image = "dynverse/ti_periodpc",
    version = dynmethods::method_versions[["dynverse/ti_periodpc"]],
  )(
    ndim = ndim,
    maxit = maxit
  )
}

