######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using PAGA
#' 
#' @description
#' Will generate a trajectory using [PAGA](https://doi.org/10.1101/208819).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_paga).
#' The original code of this method is available
#' [here](https://github.com/theislab/graph_abstraction).
#' 
#' @references Wolf, F.A., Hamey, F., Plass, M., Solana, J., Dahlin, J.S.,
#' Gottgens, B., Rajewsky, N., Simon, L., Theis, F.J., 2017. Graph abstraction
#' reconciles clustering with trajectory inference through a topology preserving
#' map of single cells.
#' 
#' @param n_neighbors integer; Number of neighbours for knn (default: `15L`;
#' range: from `1L` to `100L`)
#' @param n_comps integer; Number of principal components (default: `50L`; range:
#' from `0L` to `100L`)
#' @param n_dcs integer; Number of diffusion components for denoising graph, 0
#' means no denoising. (default: `15L`; range: from `0L` to `40L`)
#' @param resolution numeric; Resolution of louvain clustering, which determines
#' the granularity of the clustering. Higher values will result in more clusters.
#' (default: `1L`; range: from `0.1` to `10L`)
#' @param embedding_type discrete; Either 'umap' (scales very well, recommended
#' for very large datasets) or 'fa' (ForceAtlas2, often a bit more intuitive for
#' small datasets). (default: `"fa"`; values: {`"umap"`, `"fa"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_paga <- function(
    n_neighbors = 15L,
    n_comps = 50L,
    n_dcs = 15L,
    resolution = 1L,
    embedding_type = "fa",
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/ti_paga",
    version = method_versions[["dynverse/ti_paga"]],
    config = config
  )(
    n_neighbors = n_neighbors,
    n_comps = n_comps,
    n_dcs = n_dcs,
    resolution = resolution,
    embedding_type = embedding_type
  )
}

