######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using pseudogp
#' 
#' @description
#' Will generate a trajectory using
#' [pseudogp](https://doi.org/10.1371/journal.pcbi.1005212).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/pseudogp).
#' The original code of this method is available
#' [here](https://github.com/kieranrcampbell/pseudogp).
#' 
#' @references Campbell, K.R., Yau, C., 2016. Order Under Uncertainty: Robust
#' Differential Expression Analysis Using Probabilistic Models for Pseudotime
#' Inference. PLOS Computational Biology 12, e1005212.
#' 
#' @param smoothing_alpha numeric; The hyperparameter for the Gamma distribution
#' that controls arc-length (default: `10`; range: from `1` to `20`)
#' @param smoothing_beta numeric; The hyperparameter for the Gamma distribution
#' that controls arc-length (default: `3`; range: from `1` to `20`)
#' @param pseudotime_mean numeric; The mean of the constrained normal prior on the
#' pseudotimes (default: `0.5`; range: from `0` to `1`)
#' @param pseudotime_var numeric; The variance of the constrained normal prior on
#' the pseudotimes (default: `1`; range: from `0.01` to `1`)
#' @param chains integer; The number of chains for the MCMC trace (default: `3L`;
#' range: from `1L` to `20L`)
#' @param iter integer; The number of iterations for the MCMC trace (default:
#' `100L`; range: from `100L` to `1000L`)
#' @param dimreds logical_vector; A character vector specifying which
#' dimensionality reduction methods to use.See
#' \code{\link[dyndimred:dimred]{dyndimred::dimred}} for the list of available
#' dimensionality reduction methods.
#' @param initialise_from discrete; How to initialise the MCMC chain. One of
#' "random" (stan decides),"principal_curve", or "pca" (the first component of PCA
#' rescaled is taken to be the pseudotimes).Note: if multiple representations are
#' provided, \code{pseudogp} will take the principal curve orpca from the first
#' rather than combining them. If a particular representation is required, it isup
#' to the user to re-order them. (default: `"random"`; values: {`"random"`,
#' `"principal_curve"`, `"pca"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_pseudogp <- function(
    smoothing_alpha = 10,
    smoothing_beta = 3,
    pseudotime_mean = 0.5,
    pseudotime_var = 1,
    chains = 3L,
    iter = 100L,
    dimreds = c(TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    initialise_from = "random",
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/pseudogp@sha256:c35f20b1250e163d191aa9ba871343cb676984f1db118eb67ceae0532e302a3c",
    config = config
  )(
    smoothing_alpha = smoothing_alpha,
    smoothing_beta = smoothing_beta,
    pseudotime_mean = pseudotime_mean,
    pseudotime_var = pseudotime_var,
    chains = chains,
    iter = iter,
    dimreds = dimreds,
    initialise_from = initialise_from
  )
}

