######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Projected Monocle
#' 
#' @description
#' Will generate a trajectory using [Projected
#' Monocle](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/projected_monocle).
#' The original code of this method is available
#' [here](https://github.com/cole-trapnell-lab/monocle-release).
#' 
#' 
#' 
#' @param reduction_method discrete; A character string specifying the algorithm
#' to use for dimensionality reduction. (default: `"DDRTree"`; values:
#' {`"DDRTree"`})
#' @param max_components integer; The dimensionality of the reduced space
#' (default: `2L`; range: from `2L` to `20L`)
#' @param norm_method discrete; Determines how to transform expression values
#' prior to reducing dimensionality (default: `"vstExprs"`; values: {`"vstExprs"`,
#' `"log"`, `"none"`})
#' @param auto_param_selection logical; When this argument is set to TRUE
#' (default), it will automatically calculate the proper value for the ncenter
#' (number of centroids) parameters which will be passed into DDRTree call.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_projected_monocle <- function(
    reduction_method = "DDRTree",
    max_components = 2L,
    norm_method = "vstExprs",
    auto_param_selection = TRUE,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/projected_monocle@sha256:81093045e8d511dd4ee21cc284e0e5e029bc0343d628bc5c8ad193bf0188f350",
    container_type = container_type
  )(
    reduction_method = reduction_method,
    max_components = max_components,
    norm_method = norm_method,
    auto_param_selection = auto_param_selection
  )
}

