######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Random
#' 
#' @description
#' Will generate a trajectory using Random.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_random).
#' 
#' 
#' 
#' 
#' @param dummy_param Dummy parameter. Domain: U(0, 1). Default: 0.5. Format:
#' numeric.
#' 
#' @keywords method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_random <- function(
    dummy_param = 0.5
) {
  create_ti_method_container(
    container_id = "dynverse/ti_random:v0.9.9",
  )(
    dummy_param = dummy_param
  )
}

