######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Control: random
#' 
#' @description
#' Will generate a trajectory using Control: random.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/random).
#' 
#' 
#' 
#' 
#' @param dummy_param numeric; Dummy parameter (default: `0.5`; range: from `0` to
#' `1`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_random <- function(
    dummy_param = 0.5,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/random@sha256:86b52d8297070fa702fd5c7dfc61b26bf5b6cf2d5cfe5790e09380b0922c4b8c",
    config = config
  )(
    dummy_param = dummy_param
  )
}

