######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using SCORPIUS
#' 
#' @description
#' Will generate a trajectory using [SCORPIUS](https://doi.org/10.1101/079509).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_scorpius).
#' The original code of this method is available
#' [here](https://github.com/rcannood/SCORPIUS).
#' 
#' @references Cannoodt, R., Saelens, W., Sichien, D., Tavernier, S., Janssens,
#' S., Guilliams, M., Lambrecht, B.N., De Preter, K., Saeys, Y., 2016. SCORPIUS
#' improves trajectory inference and identifies novel modules in dendritic cell
#' development.
#' 
#' @param distance_method discrete; A character string indicating which
#' correlationcoefficient (or covariance) is to be computed. One of "pearson",
#' "kendall", or "spearman". (default: `"spearman"`; values: {`"spearman"`,
#' `"pearson"`, `"kendall"`})
#' @param ndim integer; The number of dimensions in the new space. (default: `3L`;
#' range: from `2L` to `20L`)
#' @param k integer; The number of clusters to cluster the data into. (default:
#' `4L`; range: from `1L` to `20L`)
#' @param thresh numeric; \code{\link[princurve]{principal_curve}} parameter:
#' convergence threshhold on shortest distances to the curve (default: `0.001`;
#' range: from `1e-05` to `1e+05`)
#' @param maxit integer; \code{\link[princurve]{principal_curve}} parameter:
#' maximum number of iterations (default: `10L`; range: from `0L` to `50L`)
#' @param stretch numeric; \code{\link[princurve]{principal_curve}} parameter: a
#' factor by which the curve can be extrapolated when points are projected
#' (default: `0`; range: from `0` to `5`)
#' @param smoother discrete; \code{\link[princurve]{principal_curve}} parameter:
#' choice of smoother (default: `"smooth_spline"`; values: {`"smooth_spline"`,
#' `"lowess"`, `"periodic_lowess"`})
#' @param sparse logical; Whether or not to use sparse MDS dimensionality
#' reduction,for datasets with large amounts of cells.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_scorpius <- function(
    distance_method = "spearman",
    ndim = 3L,
    k = 4L,
    thresh = 0.001,
    maxit = 10L,
    stretch = 0,
    smoother = "smooth_spline",
    sparse = TRUE
) {
  create_ti_method_with_container(
    container_id = "dynverse/ti_scorpius",
    version = dynmethods::method_versions[["dynverse/ti_scorpius"]],
  )(
    distance_method = distance_method,
    ndim = ndim,
    k = k,
    thresh = thresh,
    maxit = maxit,
    stretch = stretch,
    smoother = smoother,
    sparse = sparse
  )
}

