######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using SLICER
#' 
#' @description
#' Will generate a trajectory using
#' [SLICER](https://doi.org/10.1186/s13059-016-0975-3).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/slicer).
#' The original code of this method is available
#' [here](https://github.com/jw156605/SLICER).
#' 
#' @references Welch, J.D., Hartemink, A.J., Prins, J.F., 2016. SLICER: inferring
#' branched, nonlinear cellular trajectories from single cell RNA-seq data. Genome
#' Biology 17.
#' 
#' @param kmin integer; Smallest value of k to try (default: `10L`; range: from
#' `2L` to `20L`)
#' @param m integer; Intrinsic dimension of the data. This parameter mainly
#' influences the visualisation of the results. The real intrinsic dimension will
#' be calculated automaticly.  (default: `2L`; range: from `2L` to `20L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_slicer <- function(
    kmin = 10L,
    m = 2L,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/slicer@sha256:f831ba633f3e37b570b71342376df222fa629e1c269e0782be3820778e1febe3",
    container_type = container_type
  )(
    kmin = kmin,
    m = m
  )
}

