######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using SCOUP
#' 
#' @description
#' Will generate a trajectory using
#' [SCOUP](https://doi.org/10.1186/s12859-016-1109-3).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_scoup).
#' The original code of this method is available
#' [here](https://github.com/hmatsu1226/SCOUP).
#' 
#' @references Matsumoto, H., Kiryu, H., 2016. SCOUP: a probabilistic model based
#' on the Ornstein–Uhlenbeck process to analyze single-cell expression data during
#' differentiation. BMC Bioinformatics 17.
#' 
#' @param ndim integer; Number of pca dimensions (default: `2L`; range: from `2L`
#' to `20L`)
#' @param max_ite1 integer; Upper bound of EM iteration (without pseudo-time
#' optimization). (default: `100L`; range: from `2L` to `5000L`)
#' @param max_ite2 integer; Upper bound of EM iteration (including pseudo-time
#' optimization). (default: `100L`; range: from `2L` to `500000L`)
#' @param alpha_min numeric; Lower bound of alpha. (default: `0.1`; range: from
#' `0.001` to `10`)
#' @param alpha_max numeric; Upper bound of alpha. (default: `100L`; range: from
#' `1L` to `10000L`)
#' @param t_min numeric; Lower bound of pseudo-time. (default: `0.001`; range:
#' from `1e-05` to `1`)
#' @param t_max numeric; Upper bound of pseudo-time (default: `2L`; range: from
#' `0.1` to `100L`)
#' @param sigma_squared_min numeric; Lower bound of sigma squared (default: `0.1`;
#' range: from `0.001` to `10`)
#' @param thresh numeric; Threshold (default: `0.01`; range: from `0.01` to `10`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_scoup <- function(
    ndim = 2L,
    max_ite1 = 100L,
    max_ite2 = 100L,
    alpha_min = 0.1,
    alpha_max = 100L,
    t_min = 0.001,
    t_max = 2L,
    sigma_squared_min = 0.1,
    thresh = 0.01,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/ti_scoup",
    version = dynmethods::method_versions[["dynverse/ti_scoup"]],
    config = config
  )(
    ndim = ndim,
    max_ite1 = max_ite1,
    max_ite2 = max_ite2,
    alpha_min = alpha_min,
    alpha_max = alpha_max,
    t_min = t_min,
    t_max = t_max,
    sigma_squared_min = sigma_squared_min,
    thresh = thresh
  )
}

