######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using SCUBA
#' 
#' @description
#' Will generate a trajectory using
#' [SCUBA](https://doi.org/10.1073/pnas.1408993111).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_scuba).
#' The original code of this method is available
#' [here](https://github.com/gcyuan/SCUBA).
#' 
#' @references Marco, E., Karp, R.L., Guo, G., Robson, P., Hart, A.H., Trippa, L.,
#' Yuan, G.-C., 2014. Bifurcation analysis of single-cell gene expression data
#' reveals epigenetic landscape. Proceedings of the National Academy of Sciences
#' 111, E5643–E5650.
#' 
#' @param rigorous_gap_stats logical; Whether to use rigorous gap statistics to
#' determine number of clusters
#' @param N_dim integer; Number of TSNE dimensions (default: `2L`; range: from
#' `2L` to `3L`)
#' @param low_gene_threshold numeric; Threshold value for genes of low expression
#' levels (default: `1L`; range: from `0L` to `5L`)
#' @param low_gene_fraction_max numeric; Maximum fraction of lowly-expressed cells
#' allowed for each gene (default: `0.7`; range: from `0L` to `1L`)
#' @param min_split integer; Lower threshold on the number of cells in a cluster
#' for this cluster to be split. (default: `15L`; range: from `1L` to `100L`)
#' @param min_percentage_split numeric; Minimum fraction of cells in the smaller
#' cluster during a bifurcation. (default: `0.25`; range: from `0L` to `1L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_scuba <- function(
    rigorous_gap_stats = TRUE,
    N_dim = 2L,
    low_gene_threshold = 1L,
    low_gene_fraction_max = 0.7,
    min_split = 15L,
    min_percentage_split = 0.25,
    config = dynwrap::container_config()
) {
  data(repo_digests, package = "dynmethods")
  create_ti_method_with_container(
    image = "dynverse/ti_scuba",
    version = method_versions[["dynverse/ti_scuba"]],
    config = config
  )(
    rigorous_gap_stats = rigorous_gap_stats,
    N_dim = N_dim,
    low_gene_threshold = low_gene_threshold,
    low_gene_fraction_max = low_gene_fraction_max,
    min_split = min_split,
    min_percentage_split = min_percentage_split
  )
}

