######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using SCIMITAR
#' 
#' @description
#' Will generate a trajectory using
#' [SCIMITAR](https://doi.org/10.1142/9789813207813_0053).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_scimitar).
#' The original code of this method is available
#' [here](https://github.com/dimenwarper/scimitar).
#' 
#' @references CORDERO, P., STUART, J.M., 2016. TRACING CO-REGULATORY NETWORK
#' DYNAMICS IN NOISY, SINGLE-CELL TRANSCRIPTOME TRAJECTORIES. Biocomputing 2017.
#' 
#' @param covariance_type discrete; (default: `"diag"`; values: {`"diag"`,
#' `"spherical"`, `"full"`})
#' @param degree integer; (default: `3L`; range: from `1L` to `20L`)
#' @param step_size numeric; (default: `0.07`; range: from `0.01` to `0.1`)
#' @param cov_estimator discrete; (default: `"corpcor"`; values: {`"identity"`,
#' `"diag"`, `"sample"`, `"global"`, `"glasso"`, `"corpcor"`, `"average"`})
#' @param cov_reg numeric; (default: `0.05`; range: from `0.01` to `0.1`)
#' @param max_iter integer; (default: `3L`; range: from `1L` to `20L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_scimitar <- function(
    covariance_type = "diag",
    degree = 3L,
    step_size = 0.07,
    cov_estimator = "corpcor",
    cov_reg = 0.05,
    max_iter = 3L,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/ti_scimitar",
    version = dynmethods::method_versions[["dynverse/ti_scimitar"]],
    config = config
  )(
    covariance_type = covariance_type,
    degree = degree,
    step_size = step_size,
    cov_estimator = cov_estimator,
    cov_reg = cov_reg,
    max_iter = max_iter
  )
}

