#' Inferring trajectories with SLICE
#'
#' @inherit ti_angle description
#'
#' @inheritParams SLICE::getEntropy
#' @inheritParams SLICE::getLineageModel
#'
#' @export
ti_slice <- create_ti_method(
  name = "SLICE",
  short_name = "slice",
  package_loaded = c(),
  package_required = c("SLICE", "igraph"),
  parameters = list(
    distance_method = list(
      type = "discrete",
      default = "euclidean",
      values = c("euclidean", "cosine", "pearson", "spearman", "L1", "MI"),
      description = "Distance method to be used. The available distances are the Euclidean distance (method=\"euclidean\"), Manhattan distance (also called L1 distance, method=\"L1\"), cosine distance (method=\"cosine\") , distance based on Pearson (method=\"pearson\") or Spearman (method=\"spearman\") correlation coefficients, and distance based on Mutual Information (method=\"MI\"). Intervals used to assess Mutual Information are indicated in the parameter 'bins'."),

    dimred_method = list(
      type = "discrete",
      default = "none",
      values = c("none", "PCA", "ICA", "tSNE", "classical-MDS", "nonmetric-MDS"),
      description = "Dimensionality reduction algorithm to be used. Options are: Principal Component Analysis (method=\"PCA\"), Independent Component Analysis (method=\"ICA\"; using fastICA() function in fastICA package), t-Distributed Stochastic Neighbor Embedding (method=\"tSNE\"; using Rtsne() function in Rtsne package with parameters tsne.perplexity=1 and tsne.theta=0.25), classical Multidimensional Scaling (method=\"classical-MDS\"; using the cmdscale() function) and non-metric Multidimensional Scaling (method=\"nonmetric-MDS\";using the isoMDS() function in MASS package). if method=\"PCA\" is chosen, the proportion of variance explained by each of the principal axes is plotted. We note that Sincell makes use of the Rtsne implementation of the Barnes-Hut algorithm, which approximates the likelihood. The user should be aware that this is a less accurate version of t-SNE than e.g. the one used as basis of viSNE (Amir,E.D. et al. 2013, Nat Biotechnol 31, 545-552)."),

    clust.method = list(
      type = "discrete",
      default = "max.distance",
      values = c("max.distance", "percent", "knn", "k-medoids", "ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid"),
      description = "\nIf clust.method=\"max.distance\", clusters are defined as subgraphs generated by a maximum pair-wise distance cut-off, that is: from a totally connected graph where all cells are connected to each other, the algorithm only keeps pairs of cells connected by a distance lower than a given threshold.\n\nIf clust.method=\"percent\", clusters are defined as subgraphs generated by a given rank-percentile of the shortest pair-wise distances, that is; from a totally connected graph where all cells are connected to each other, the algorithm only keeps the top 'x' percent of shortest pairwise distances as indicated by \"shortest.rank.percent\".\n\nIf clust.method=\"knn\", unsupervised K-Nearest Neighbors (K-NN) clustering is performed: From a totally disconnected graph where none of the cells are connected to each other, the algorithm connects each cell to its 'k' nearest neighbors. If parameter \"mutual=TRUE\", Unsupervised K-Mutual Nearest Neighbours (K-MNN) clustering is performed, that is: only reciprocal k nearest neighbors are connected.\n\nIf clust.method=\"k-medoids\", clustering around medoids (a more robust version of k-means) is performed with function \"pam\" from package \"cluster\" on the distance matrix in mySincellObject[[\"cell2celldist\"]] with a desired number of groups indicated in parameter \"num.clusters\"\n\nHierarchical agglomerative clustering can be performed by internally calling function \"hclust\" where the agglomeration method is indicated in parameter \"clust.method\" as one of \"ward.D\", \"ward.D2\", \"single\", \"complete\", \"average\" (= UPGMA), \"mcquitty\" (= WPGMA), \"median\" (= WPGMC) or \"centroid\" (= UPGMC). Clusters are obtained by cutting the tree produced by hclust with function cutree with a desired number of groups indicated in parameter \"num.clusters\" \n\n"),
    mutual = list(
      type = "logical",
      default = TRUE,
      description = "\nIf clust.method=\"knn\" and \"mutual=TRUE\", Unsupervised K-Mutual Nearest Neighbours (K-MNN) clustering is performed, that is: only reciprocal k nearest neighbors are connected.\n"),
    max.distance = list(
      type = "numeric",
      default = 0,
      upper = 5,
      lower = 0,
      description = "\nin max.distance algorithm, select up to which distance the points will be linked\n"),
    k = list(
      type = "integer",
      default = 3L,
      upper = 99L,
      lower = 1L,
      description = "\nIf clust.method=\"knn\", k is an integer specifying the number of nearest neighbors to consider in K-NN and K-KNN\n"),
    shortest.rank.percent = list(
      type = "numeric",
      default = 10,
      upper = 100,
      lower = 0,
      description = "\nin percent algorithm, select the percent of shortest distances will be represented as links\n"),
    graph.algorithm = list(
      type = "discrete",
      default = "MST",
      values = c("MST", "SST", "IMC"),
      description = "\nGraph building algorithm to be used: the Minimum Spanning Tree \n(graph.algorithm=\"MST\"), the Maximum Similarity Spanning Tree \n(graph.algorithm=\"SST\") and the Iterative Mutual Clustering Graph \n(graph.algorithm=\"IMC\").\n"),

    graph.using.cells.clustering = list(
      type = "logical",
      default = FALSE,
      description = "\nIf graph.using.cells.clustering=TRUE and graph.algorithm=\"MST\" or graph.algorithm=\"MST\", a precalculated clustering of cells is used. The clustering of cells is taken from SincellObject[[\"cellsClustering\"]] as calculated by function sc_clusterObj().\n"),
    k_imc = list(
      type = "integer",
      default = 3L,
      upper = 99L,
      lower = 1L,
      description = "If IMC algorithm is selected, the number of nearest neighbors used in the underlying K-Mutual Nearest Neighbour (K-MNN) algorithm is set to k."),
    pct_leaf_node_cutoff = list(
      type = "numeric",
      default = 0.5,
      upper = 0.8,
      lower = 0.01,
      description = "Leaf nodes are iteratively removed until the percentage of leaf nodes is below the given cutoff. Removed nodes are projected to their closest neighbour. This is to constrain the number of milestones being created.")
  ),
  run_fun = "dynmethods::run_slice",
  plot_fun = "dynmethods::plot_slice"
)

run_slice <- function(
  expression,
  groups_id = NULL,
  features_id = NULL,
  lm.method = "clustering",
  model.type = "tree",
  ss.method = "all",
  ss.threshold = 0.25,
  community.method = "louvain",
  cluster.method = "kmeans",
  k = 0,
  k.max = 10,
  B = 100,
  k.opt.method = "firstmax"
) {
  requireNamespace("SLICE")
  requireNamespace("igraph")

  # if k is 0, set to NULL
  if (k == 0) {
    k <- NULL
  }

  # if groups_id is not given, fill it with 1's
  if(!is.null(groups_id)) {
    cellidentity <- groups_id %>%
      slice(match(rownames(expression), cell_id)) %>%
      pull(group_id) %>%
      factor()
  } else {
    cellidentity <- factor(rep(1, nrow(expression)))
  }

  # TIMING: done with preproc
  tl <- add_timing_checkpoint(NULL, "method_afterpreproc")

  # wrap data
  sc <- SLICE::construct(
    exprmatrix = as.data.frame(t(expression)),
    cellidentity = cellidentity
  )

  num_genes <- ncol(expression)
  km <- matrix(
    runif(num_genes * num_genes),
    ncol = num_genes,
    dimnames = list(colnames(expression), colnames(expression))
  )

  # calculate the entropy of individual cells
  sc <- SLICE::getEntropy(sc, km = km)

  # reduce expression space
  sc <- SLICE::getRDS(
    sc,
    method = "pca",
    num_dim = 2,
    log.base = 2,
    do.center = TRUE,
    do.scale = FALSE,
    use.cor = TRUE,
    min.var = 0,
    min.cells = 0,
    genes.use = features_id
  )

  # infer entropy-directed cell lineage model
  sc <- SLICE::getLineageModel(
    sc,
    model.type = model.type,
    ss.method = ss.method,
    ss.threshold = ss.threshold,
    community.method = community.method,
    cluster.method = cluster.method,
    k = k,
    k.max = k.max,
    B = B,
    k.opt.method = k.opt.method,
    do.plot = FALSE
  )

  # TIMING: done with method
  tl <- tl %>% add_timing_checkpoint("method_aftermethod")

  # extract the milestone ids
  lin_model <- sc@model$lineageModel
  milestone_ids <- names(igraph::V(lin_model))

  # extract the milestone network
  milestone_network <- lin_model %>%
    igraph::as_data_frame() %>%
    rename(length = weight) %>%
    mutate(directed = TRUE)

  # extract the pseudotime
  pseudotime <- map_df(seq_len(nrow(milestone_network)), function(i) {
    from <- milestone_network[i, 1]
    to <- milestone_network[i, 2]
    sc_tmp <- SLICE::getTrajectories(
      sc,
      method = "pc",
      start = match(from, milestone_ids),
      end = match(to, milestone_ids),
      do.plot = FALSE,
      do.trim = FALSE
    )
    sc_tmp@transitions[[1]]$i.pseudotime %>%
      tibble::rownames_to_column("cell_id") %>%
      mutate(from = from, to = to) %>%
      select(cell_id, from, to, percentage = ptime)
  })

  # check whether the state of a cell is in the network's
  # from or to, and get the earliest timepoint
  progressions <- sc@model$cells.df %>%
    tibble::rownames_to_column("cell_id") %>%
    slice(match(rownames(expression), cell_id)) %>%
    mutate(state = paste0("slice.ss.", slice.state)) %>%
    select(cell_id, state) %>%
    right_join(pseudotime, by = "cell_id") %>%
    filter((state == from) | (state == to)) %>%
    group_by(cell_id) %>%
    arrange(percentage) %>%
    slice(1) %>%
    select(-state) %>%
    ungroup()

  # collect data for visualisation
  cells.df <- sc@model$cells.df
  edge.df <- igraph::get.edgelist(lin_model) %>%
    as.data.frame() %>%
    mutate(
      ix = match(V1, rownames(cells.df)),
      iy = match(V2, rownames(cells.df)),
      src.x = cells.df$x[ix],
      src.y = cells.df$y[ix],
      dst.x = cells.df$x[iy],
      dst.y = cells.df$y[iy]
    )

  dimred <- cells.df %>%
    tibble::rownames_to_column("cell_id") %>%
    filter(slice.realcell == 1) %>%
    tibble::column_to_rownames("cell_id") %>%
    select(x, y) %>%
    as.matrix()

  dimred_milestones <- cells.df %>%
    tibble::rownames_to_column("cell_id") %>%
    filter(slice.realcell == 0) %>%
    tibble::column_to_rownames("cell_id") %>%
    select(x, y) %>%
    as.matrix()



  # return output
  wrap_prediction_model(
    cell_ids = rownames(expression)
  ) %>% add_trajectory(
    milestone_ids = milestone_ids,
    milestone_network = milestone_network,
    progressions = progressions,
    divergence_regions = NULL
  ) %>% add_dimred(
    dimred = dimred,
    dimred_milestones = dimred_milestones,
    dimred_trajectory_segments = edge.df[,c("src.x", "src.y", "dst.x", "dst.y")] %>%
      mutate_all(as.numeric) %>%
      as.matrix %>%
      magrittr::set_colnames(c("from_comp_1", "from_comp_2", "to_comp_1", "to_comp_2")),
    cells.df = cells.df, # todo: remove this and modify plot function
    edge.df = edge.df
  ) %>% add_timings(
    timings = tl %>% add_timing_checkpoint("method_afterpostproc")
  )
}

#' @importFrom grid arrow
plot_slice <- function(prediction) {
  requireNamespace("igraph")

  # Adapted from SLICE code
  cells.df <- prediction$cells.df
  edge.df <- prediction$edge.df

  # split up the "cells"
  milestones <- cells.df %>% subset(slice.realcell == 0)
  cells_stable <- cells.df %>% subset(slice.realcell==1 & slice.stablestate != "NA")
  cells_unstable <- cells.df %>% subset(slice.realcell==1 & slice.stablestate == "NA")

  # make plot
  g <- ggplot(mapping = aes(x, y, size = entropy)) +
    geom_point(aes(col = slice.state), cells_stable) +
    geom_point(aes(col = slice.state), cells_unstable) +
    geom_segment(aes(x = src.x, y = src.y, xend = dst.x, yend = dst.y), edge.df,
                 size = 2, linetype = "solid", col = "black",
                 alpha = 0.6, arrow = grid::arrow(), na.rm = TRUE) +
    geom_point(data = milestones, col = "black") +
    theme(legend.position = c(.92, .2)) +
    labs(colour = "Group", size = "Entropy")
  process_dynplot(g, prediction$id)
}
