######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using scTDA
#' 
#' @description
#' Will generate a trajectory using [scTDA](https://doi.org/101010101/1101010101).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/sctda).
#' The original code of this method is available
#' [here](https://github.com/dynverse/template).
#' 
#' @references
#' 
#' @param param1 integer; Description of param1 (default: `5L`; range: from `1L`
#' to `10L`)
#' @param param2 discrete; Description of param2 (default: `"one"`; values:
#' {`"one"`, `"two"`, `"three"`})
#' @param param3 numeric; Description of param3 (default: `0.5`; range: from `0`
#' to `1`)
#' @param param4 logical; Description of param4
#' @inheritParams dynwrap::create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_sctda <- function(
    param1 = 5L,
    param2 = "one",
    param3 = 0.5,
    param4 = TRUE,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/sctda",
    run_environment = run_environment,
    param1 = param1,
    param2 = param2,
    param3 = param3,
    param4 = param4
  )
}

