######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using shuffle
#' 
#' @description
#' Will generate a trajectory using shuffle.
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_shuffle).
#' 
#' 
#' 
#' 
#' @param dummy_param Dummy parameter. Default: TRUE. Format: logical.
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_shuffle <- function(
    dummy_param = TRUE
) {
  create_ti_method_container(
    container_id = "dynverse/ti_shuffle:v0.9.9",
  )(
    dummy_param = dummy_param
  )
}

