######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using STEMNET
#' 
#' @description
#' Will generate a trajectory using [STEMNET](https://doi.org/10.1038/ncb3493).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/stemnet).
#' The original code of this method is available
#' [here](https://git.embl.de/velten/STEMNET).
#' 
#' @references Velten, L., Haas, S.F., Raffel, S., Blaszkiewicz, S., Islam, S.,
#' Hennig, B.P., Hirche, C., Lutz, C., Buss, E.C., Nowak, D., Boch, T., Hofmann,
#' W.-K., Ho, A.D., Huber, W., Trumpp, A., Essers, M.A.G., Steinmetz, L.M., 2017.
#' Human haematopoietic stem cell lineage commitment is a continuous process.
#' Nature Cell Biology 19, 271–281.
#' 
#' @param alpha numeric; The elastic net mixing parameter of the ‘glmnet’
#' classifier. (default: `0.1`; range: from `0.001` to `10L`)
#' @param lambda_auto logical; Whether to select the lambda by cross-validation
#' @param lambda numeric; The lambda penalty of GLM. (default: `0.1`; range: from
#' `0.05` to `1L`)
#' @param force logical; Do not use! This is a parameter to force FateID to run on
#' benchmark datasets where not enough end groups are present.
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_stemnet <- function(
    alpha = 0.1,
    lambda_auto = TRUE,
    lambda = 0.1,
    force = FALSE,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/stemnet@sha256:09e82ff5c4b6a482af20ba355170d27523fa52056b08fad1f0ca193b5c199f6b",
    container_type = container_type
  )(
    alpha = alpha,
    lambda_auto = lambda_auto,
    lambda = lambda,
    force = force
  )
}

