######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using TSCAN
#' 
#' @description
#' Will generate a trajectory using [TSCAN](https://doi.org/10.1093/nar/gkw430).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_tscan).
#' The original code of this method is available
#' [here](https://github.com/zji90/TSCAN).
#' 
#' @references Ji, Z., Ji, H., 2016. TSCAN: Pseudo-time reconstruction and
#' evaluation in single-cell RNA-seq analysis. Nucleic Acids Research 44,
#' e117–e117.
#' 
#' @param minexpr_percent Parameter; , Domain: U(0, 1), Default: 0, Format:
#' numeric.
#' @param minexpr_value Parameter; , Domain: U(0, 10), Default: 0, Format:
#' numeric.
#' @param cvcutoff Parameter; , Domain: U(0, 5), Default: 0, Format: numeric.
#' @param clusternum_lower Parameter; , Domain: U(2, 20), Default: 2, Format:
#' integer.
#' @param clusternum_upper Parameter; , Domain: U(2, 20), Default: 9, Format:
#' integer.
#' @param modelNames Parameter; , Domain: {EII, VII, EEI, VEI, EVI, VVI, EEE, EVE,
#' VEE, VVE, EEV, VEV, EVV, VVV}, Default: VVV, Format: character.
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_tscan <- function(
    minexpr_percent = 0,
    minexpr_value = 0,
    cvcutoff = 0,
    clusternum_lower = 2L,
    clusternum_upper = 9L,
    modelNames = "VVV"
) {
  create_ti_method_container(
    container_id = "dynverse/ti_tscan:v0.9.9",
  )(
    minexpr_percent = minexpr_percent,
    minexpr_value = minexpr_value,
    cvcutoff = cvcutoff,
    clusternum_lower = clusternum_lower,
    clusternum_upper = clusternum_upper,
    modelNames = modelNames
  )
}

