######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using TSCAN
#' 
#' @description
#' Will generate a trajectory using [TSCAN](https://doi.org/10.1093/nar/gkw430).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/tscan).
#' The original code of this method is available
#' [here](https://github.com/zji90/TSCAN).
#' 
#' @references Ji, Z., Ji, H., 2016. TSCAN: Pseudo-time reconstruction and
#' evaluation in single-cell RNA-seq analysis. Nucleic Acids Research 44,
#' e117–e117.
#' 
#' @param minexpr_percent numeric; (default: `0`; range: from `0` to `1`)
#' @param minexpr_value numeric; (default: `0`; range: from `0` to `10`)
#' @param cvcutoff numeric; (default: `0`; range: from `0` to `5`)
#' @param clusternum_lower integer; (default: `2L`; range: from `2L` to `20L`)
#' @param clusternum_upper integer; (default: `9L`; range: from `2L` to `20L`)
#' @param modelNames discrete; (default: `"VVV"`; values: {`"EII"`, `"VII"`,
#' `"EEI"`, `"VEI"`, `"EVI"`, `"VVI"`, `"EEE"`, `"EVE"`, `"VEE"`, `"VVE"`,
#' `"EEV"`, `"VEV"`, `"EVV"`, `"VVV"`})
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_tscan <- function(
    minexpr_percent = 0,
    minexpr_value = 0,
    cvcutoff = 0,
    clusternum_lower = 2L,
    clusternum_upper = 9L,
    modelNames = "VVV",
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/tscan@sha256:f499f47be4af7c5489f065c34fe4b3a77e44efb0902875b3e28359f5fda32dfe",
    container_type = container_type
  )(
    minexpr_percent = minexpr_percent,
    minexpr_value = minexpr_value,
    cvcutoff = cvcutoff,
    clusternum_lower = clusternum_lower,
    clusternum_upper = clusternum_upper,
    modelNames = modelNames
  )
}

