######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using topslam
#' 
#' @description
#' Will generate a trajectory using [topslam](https://doi.org/10.1101/057778).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_topslam).
#' The original code of this method is available
#' [here](https://github.com/mzwiessele/topslam).
#' 
#' @references Zwiessele, M., Lawrence, N.D., 2016. Topslam: Waddington Landscape
#' Recovery for Single Cell Experiments.
#' 
#' @param n_components integer; The number of components (default: `2L`; range:
#' from `2L` to `10L`)
#' @param n_neighbors integer; The number of neighbors (default: `10L`; range:
#' from `2L` to `100L`)
#' @param linear_dims integer; (default: `0L`; range: from `0L` to `5L`)
#' @param max_iters integer; The number of iterations to optimize over (default:
#' `1000L`; range: from `10L` to `10000L`)
#' @param dimreds logical_vector; Which dimensionality reductions to use; tSNE,
#' PCA, Spectral, Isomap and/or ICA
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_topslam <- function(
    n_components = 2L,
    n_neighbors = 10L,
    linear_dims = 0L,
    max_iters = 1000L,
    dimreds = c(TRUE, TRUE, TRUE, TRUE, TRUE),
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/ti_topslam",
    version = dynmethods::method_versions[["dynverse/ti_topslam"]],
    config = config
  )(
    n_components = n_components,
    n_neighbors = n_neighbors,
    linear_dims = linear_dims,
    max_iters = max_iters,
    dimreds = dimreds
  )
}

