######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using URD
#' 
#' @description
#' Will generate a trajectory using
#' [URD](https://doi.org/10.1126/science.aar3131).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/urd).
#' The original code of this method is available
#' [here](https://github.com/farrellja/URD).
#' 
#' @references Farrell, J.A., Wang, Y., Riesenfeld, S.J., Shekhar, K., Regev, A.,
#' Schier, A.F., 2018. Single-cell reconstruction of developmental trajectories
#' during zebrafish embryogenesis. Science 360, eaar3131.
#' 
#' @param knn integer; Number of nearest neighbors to use. `0` takes a guess.
#' (default: `0L`; range: from `0L` to `50L`)
#' @param sigma.use numeric; Kernel width to use for the diffusion map. `0` uses
#' destiny's global auto-detection procedure. (default: `0`; range: from `0` to
#' `1`)
#' @param distance discrete; Distance metric to use for determining transition
#' probabilities. (default: `"euclidean"`; values: {`"euclidean"`, `"cosine"`,
#' `"rankcor"`})
#' @param n_floods integer; Number of simulations to perform and average.
#' (default: `20L`; range: from `5L` to `50L`)
#' @param stability.div numeric; Number of simulation subsamplings to calculate.
#' (default: `10L`; range: from `2L` to `50L`)
#' @param mp.factor numeric; Retain PCs than are this factor more than the
#' estimated maximum singular value expected or random data. This is useful in
#' cases when there are many PCs that have standard deviations just above that
#' expected by random, which probably represent noise and should be excluded.
#' (default: `1L`; range: from `0L` to `10L`)
#' @param perplexity numeric; Perplexity parameter for the tSNE. (default: `30L`;
#' range: from `0L` to `100L`)
#' @param theta numeric; Speed/accuracy trade-off for Barnes-Hut approximation of
#' tSNE. 0 is exact tSNE, higher is less accurate. (default: `0.5`; range: from
#' `0L` to `1L`)
#' @param max_iter integer; Number of nearest neighbors to use. `0` takes a guess.
#' (default: `1000L`; range: from `100L` to `10000L`)
#' @param num.nn integer; How many nearest-neighbors to use in the k-nn graph.
#' (default: `30L`; range: from `10L` to `100L`)
#' @param do.jaccard logical; Weight edges in the k-nn graph according to their
#' Jaccard overlap?
#' @param optimal.cells.forward numeric; The number of cells in the direction
#' specified by pseudotime.direction at which the logistic should reach
#' 1-asymptote. (default: `20L`; range: from `5L` to `100L`)
#' @param max.cells.back numeric; The number of cells in the direction opposite
#' from that specified by pseudotime.direction at which the logistic should reach
#' asymptote. (default: `40L`; range: from `5L` to `200L`)
#' @param n.per.tip integer; Number of walks to do per tip. (default: `25000L`;
#' range: from `100L` to `1000000L`)
#' @param root.visits integer; Number of steps to take that visit a root.cell
#' before stopping. (default: `1L`; range: from `1L` to `5L`)
#' @param max.steps integer; Number of walks to do per tip. (default: `25000L`;
#' range: from `100L` to `1000000L`)
#' @param n.subsample integer; Number of subsamplings to perform for calculating
#' stability. (default: `10L`; range: from `2L` to `100L`)
#' @param divergence.method discrete; Distance metric to use for determining
#' transition probabilities. (default: `"ks"`; values: {`"ks"`, `"preference"`})
#' @param cells.per.pseudotime.bin integer; Approximate number of cells to assign
#' to each pseudotime bin for branchpoint finding. (default: `80L`; range: from
#' `10L` to `1000L`)
#' @param bins.per.pseudotime.window integer; Width of moving window in pseudotime
#' used for branchpoint finding, in terms of bins. (default: `5L`; range: from
#' `2L` to `20L`)
#' @param p.thresh numeric; P-value threshold to use in determining whether
#' visitation is significantly different from pairs of tips (default: `0.01`;
#' range: from `1e-05` to `1L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_urd <- function(
    knn = 0L,
    sigma.use = 0,
    distance = "euclidean",
    n_floods = 20L,
    stability.div = 10L,
    mp.factor = 1L,
    perplexity = 30L,
    theta = 0.5,
    max_iter = 1000L,
    num.nn = 30L,
    do.jaccard = TRUE,
    optimal.cells.forward = 20L,
    max.cells.back = 40L,
    n.per.tip = 25000L,
    root.visits = 1L,
    max.steps = 25000L,
    n.subsample = 10L,
    divergence.method = "ks",
    cells.per.pseudotime.bin = 80L,
    bins.per.pseudotime.window = 5L,
    p.thresh = 0.01,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/urd@sha256:5a5634b2a20096615f300376e9bd6830a817d3fe073a14ceb91ad9cfa6ff1490",
    container_type = container_type
  )(
    knn = knn,
    sigma.use = sigma.use,
    distance = distance,
    n_floods = n_floods,
    stability.div = stability.div,
    mp.factor = mp.factor,
    perplexity = perplexity,
    theta = theta,
    max_iter = max_iter,
    num.nn = num.nn,
    do.jaccard = do.jaccard,
    optimal.cells.forward = optimal.cells.forward,
    max.cells.back = max.cells.back,
    n.per.tip = n.per.tip,
    root.visits = root.visits,
    max.steps = max.steps,
    n.subsample = n.subsample,
    divergence.method = divergence.method,
    cells.per.pseudotime.bin = cells.per.pseudotime.bin,
    bins.per.pseudotime.window = bins.per.pseudotime.window,
    p.thresh = p.thresh
  )
}

