######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Wishbone
#'
#' @description
#' Will generate a trajectory using [Wishbone](https://doi.org/10.1038/nbt.3569).
#'
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/wishbone).
#' The original code of this method is available
#' [here](https://github.com/ManuSetty/wishbone).
#'
#' @references Setty, M., Tadmor, M.D., Reich-Zeliger, S., Angel, O., Salame,
#' T.M., Kathail, P., Choi, K., Bendall, S., Friedman, N., Pe’er, D., 2016.
#' Wishbone identifies bifurcating developmental trajectories from single-cell
#' data. Nature Biotechnology 34, 637–645.
#'
#' @param normalise logical;
#' @param knn integer; K-nearest neighbours for diffusion (default: `25L`; range:
#' from `15L` to `100L`)
#' @param n_diffusion_components integer; Number of diffusion components (default:
#' `3L`; range: from `3L` to `20L`)
#' @param n_pca_components integer; Number of pca components (default: `30L`;
#' range: from `15L` to `100L`)
#' @param k integer; K parameter (default: `25L`; range: from `15L` to `100L`)
#' @param num_waypoints integer; Number of waypoints (default: `250L`; range: from
#' `100L` to `500L`)
#' @param epsilon numeric; Epsilon (default: `1L`; range: from `0.1` to `5L`)
#' @param branch logical; Whether to allow a single bifurcation within the
#' trajectory (wishbone versus wanderlust)
#' @inheritParams dynwrap::create_ti_method_with_container
#'
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_wishbone <- function(
    normalise = TRUE,
    knn = 25L,
    n_diffusion_components = 3L,
    n_pca_components = 30L,
    k = 25L,
    num_waypoints = 250L,
    epsilon = 1L,
    branch = TRUE,
    container_type = NULL
) {
  create_ti_method_with_container(
    image = "dynverse/wishbone@sha256:28aa2af53af951a7511d383ab8e4ffb8fa6d988ca9701d9b295f73e983e23994",
    container_type = container_type
  )(
    normalise = normalise,
    knn = knn,
    n_diffusion_components = n_diffusion_components,
    n_pca_components = n_pca_components,
    k = k,
    num_waypoints = num_waypoints,
    epsilon = epsilon,
    branch = branch
  )
}

