######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Wanderlust
#' 
#' @description
#' Will generate a trajectory using
#' [Wanderlust](https://doi.org/10.1016/j.cell.2014.04.005).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/ti_wanderlust).
#' The original code of this method is available
#' [here](https://github.com/ManuSetty/wishbone).
#' 
#' @references Bendall, S.C., Davis, K.L., Amir, E.D., Tadmor, M.D., Simonds,
#' E.F., Chen, T.J., Shenfeld, D.K., Nolan, G.P., Pe’er, D., 2014. Single-Cell
#' Trajectory Detection Uncovers Progression and Regulatory Coordination in Human
#' B Cell Development. Cell 157, 714–725.
#' 
#' @param normalise logical;
#' @param knn integer; K-nearest neighbours for diffusion (default: `25L`; range:
#' from `15L` to `100L`)
#' @param n_diffusion_components integer; Number of diffusion components (default:
#' `3L`; range: from `3L` to `20L`)
#' @param n_pca_components integer; Number of pca components (default: `30L`;
#' range: from `15L` to `100L`)
#' @param k integer; K parameter (default: `25L`; range: from `15L` to `100L`)
#' @param num_waypoints integer; Number of waypoints (default: `250L`; range: from
#' `100L` to `500L`)
#' @param epsilon numeric; Epsilon (default: `1L`; range: from `0.1` to `5L`)
#' @inheritParams dynwrap::create_ti_method_with_container
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_wanderlust <- function(
    normalise = TRUE,
    knn = 25L,
    n_diffusion_components = 3L,
    n_pca_components = 30L,
    k = 25L,
    num_waypoints = 250L,
    epsilon = 1L,
    config = dynwrap::container_config()
) {
  create_ti_method_with_container(
    image = "dynverse/ti_wanderlust",
    version = dynmethods::method_versions[["dynverse/ti_wanderlust"]],
    config = config
  )(
    normalise = normalise,
    knn = knn,
    n_diffusion_components = n_diffusion_components,
    n_pca_components = n_pca_components,
    k = k,
    num_waypoints = num_waypoints,
    epsilon = epsilon
  )
}

