######################################### DO NOT EDIT! #########################################
#### This file is automatically generated from data-raw/2-generate_r_code_from_containers.R ####
################################################################################################

#' @title Inferring a trajectory inference using Waterfall
#' 
#' @description
#' Will generate a trajectory using
#' [Waterfall](https://doi.org/10.1016/j.stem.2015.07.013).
#' 
#' This method was wrapped inside a
#' [container](https://github.com/dynverse/dynmethods/tree/master/containers/waterfall).
#' The original code of this method is available
#' [here](http://www.cell.com/cms/attachment/2038326541/2052521637/mmc9.zip).
#' 
#' @references Shin, J., Berg, D.A., Zhu, Y., Shin, J.Y., Song, J., Bonaguidi,
#' M.A., Enikolopov, G., Nauen, D.W., Christian, K.M., Ming, G., Song, H., 2015.
#' Single-Cell RNA-Seq with Waterfall Reveals Molecular Cascades underlying Adult
#' Neurogenesis. Cell Stem Cell 17, 360–372.
#' 
#' @param num_clusters integer; (default: `10`; range: from `2` to `20`)
#' @inheritParams create_container_ti_method
#' 
#' @return A TI method wrapper to be used together with
#' \code{\link[dynwrap:infer_trajectories]{infer_trajectory}}
#' @export
ti_waterfall <- function(
    num_clusters = 10,
    run_environment = NULL
) {
  create_container_ti_method(
    docker_repository = "dynverse/waterfall",
    run_environment = run_environment,
    num_clusters = num_clusters
  )
}

